-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2_spectrometer_simulink_CRD\CordicKernelMag.vhd
-- Created: 2025-12-01 03:44:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CordicKernelMag
-- Source Path: lab2_spectrometer_simulink_CRD/Subsystem/HDL_CMA_core/CordicKernelMag
-- Hierarchy Level: 2
-- Model version: 1.31
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CordicKernelMag IS
  PORT( xin                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        yin                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        idx                               :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        xout                              :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        yout                              :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En14
        );
END CordicKernelMag;


ARCHITECTURE rtl OF CordicKernelMag IS

  -- Signals
  SIGNAL yin_signed                       : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yLessThanZero                    : std_logic;
  SIGNAL xin_signed                       : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL idx_unsigned                     : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL dynamic_shift_cast               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL yShifted                         : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xout2                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xout1                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xout_tmp                         : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL dynamic_shift_cast_1             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL xShifted                         : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout2                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout1                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout_tmp                         : signed(20 DOWNTO 0);  -- sfix21_En14

BEGIN
  yin_signed <= signed(yin);

  
  yLessThanZero <= '1' WHEN yin_signed < to_signed(16#000000#, 21) ELSE
      '0';

  xin_signed <= signed(xin);

  idx_unsigned <= unsigned(idx);

  dynamic_shift_cast <= resize(idx_unsigned, 8);
  yShifted <= SHIFT_RIGHT(yin_signed, to_integer(dynamic_shift_cast));

  xout2 <= xin_signed + yShifted;

  xout1 <= xin_signed - yShifted;

  
  xout_tmp <= xout2 WHEN yLessThanZero = '0' ELSE
      xout1;

  xout <= std_logic_vector(xout_tmp);

  dynamic_shift_cast_1 <= resize(idx_unsigned, 8);
  xShifted <= SHIFT_RIGHT(xin_signed, to_integer(dynamic_shift_cast_1));

  yout2 <= yin_signed - xShifted;

  yout1 <= yin_signed + xShifted;

  
  yout_tmp <= yout2 WHEN yLessThanZero = '0' ELSE
      yout1;

  yout <= std_logic_vector(yout_tmp);

END rtl;

