-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2_spectrometer_simulink_CRD\Quadrant_Mapper.vhd
-- Created: 2025-12-01 03:44:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Quadrant_Mapper
-- Source Path: lab2_spectrometer_simulink_CRD/Subsystem/HDL_CMA_core/Quadrant_Mapper
-- Hierarchy Level: 2
-- Model version: 1.31
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Quadrant_Mapper IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        xin                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        yin                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        xout                              :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        yout                              :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En14
        );
END Quadrant_Mapper;


ARCHITECTURE rtl OF Quadrant_Mapper IS

  -- Signals
  SIGNAL xin_signed                       : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL abs_rsvd_y                       : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL abs_rsvd_cast                    : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL xAbs                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xAbsReg                          : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin_signed                       : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL abs_rsvd_y_1                     : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL abs_rsvd_cast_1                  : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL yAbs                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yAbsReg                          : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL XGreaterThanY                    : std_logic;  -- ufix1
  SIGNAL xout_1                           : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout_1                           : signed(20 DOWNTO 0);  -- sfix21_En14

BEGIN
  xin_signed <= signed(xin);

  abs_rsvd_cast <= resize(xin_signed, 22);
  
  abs_rsvd_y <=  - (abs_rsvd_cast) WHEN xin_signed < to_signed(16#000000#, 21) ELSE
      resize(xin_signed, 22);
  xAbs <= abs_rsvd_y(20 DOWNTO 0);

  DelayxAbs_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xAbsReg <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xAbsReg <= xAbs;
      END IF;
    END IF;
  END PROCESS DelayxAbs_process;


  yin_signed <= signed(yin);

  abs_rsvd_cast_1 <= resize(yin_signed, 22);
  
  abs_rsvd_y_1 <=  - (abs_rsvd_cast_1) WHEN yin_signed < to_signed(16#000000#, 21) ELSE
      resize(yin_signed, 22);
  yAbs <= abs_rsvd_y_1(20 DOWNTO 0);

  DelayyAbs_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yAbsReg <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yAbsReg <= yAbs;
      END IF;
    END IF;
  END PROCESS DelayyAbs_process;


  
  XGreaterThanY <= '1' WHEN xAbsReg > yAbsReg ELSE
      '0';

  
  xout_1 <= yAbsReg WHEN XGreaterThanY = '0' ELSE
      xAbsReg;

  xout <= std_logic_vector(xout_1);

  
  yout_1 <= xAbsReg WHEN XGreaterThanY = '0' ELSE
      yAbsReg;

  yout <= std_logic_vector(yout_1);

END rtl;

