-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\DDC.vhd
-- Created: 2025-12-01 13:59:59
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DDC
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/DDC
-- Hierarchy Level: 1
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DDC IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_2_1                         :   IN    std_logic;
        valid                             :   IN    std_logic;
        signal_out                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        valid_out                         :   OUT   std_logic
        );
END DDC;


ARCHITECTURE rtl OF DDC IS

  -- Component Declarations
  COMPONENT Chirp
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          valid_in                        :   IN    std_logic;
          signal_out                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT LO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          validIn                         :   IN    std_logic;
          cosine                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT LPF
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          signal_in                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          valid_in                        :   IN    std_logic;
          signal_out                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Chirp
    USE ENTITY work.Chirp(rtl);

  FOR ALL : LO
    USE ENTITY work.LO(rtl);

  FOR ALL : LPF
    USE ENTITY work.LPF(rtl);

  -- Signals
  SIGNAL X                                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL chirp_valid                      : std_logic;
  SIGNAL X_signed                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL LO_out1                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL mix_valid                        : std_logic;
  SIGNAL LO_out1_signed                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL LO_out1_1                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Mixer_mul_temp                   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Xmix                             : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL mix_valid_1                      : std_logic;
  SIGNAL Xmix_valid                       : std_logic;
  SIGNAL Xfilter                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL LPF_valid_out                    : std_logic;
  SIGNAL Xfilter_signed                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Xfilter_1                        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Downsample_Signal_bypass_reg     : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Xdown                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL LPF_valid_out_1                  : std_logic;
  SIGNAL Downsample_Valid_bypass_reg      : std_logic;  -- ufix1
  SIGNAL Xdown_1                          : std_logic;

BEGIN
  u_Chirp : Chirp
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              valid_in => valid,
              signal_out => X,  -- sfix16_En14
              valid_out => chirp_valid
              );

  u_LO : LO
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              validIn => valid,
              cosine => LO_out1,  -- sfix16_En14
              validOut => mix_valid
              );

  u_LPF : LPF
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              signal_in => std_logic_vector(Xmix),  -- sfix16_En14
              valid_in => Xmix_valid,
              signal_out => Xfilter,  -- sfix16_En15
              valid_out => LPF_valid_out
              );

  X_signed <= signed(X);

  LO_out1_signed <= signed(LO_out1);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      LO_out1_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        LO_out1_1 <= LO_out1_signed;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  Mixer_mul_temp <= X_signed * LO_out1_1;
  Xmix <= Mixer_mul_temp(29 DOWNTO 14);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mix_valid_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        mix_valid_1 <= mix_valid;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  Xmix_valid <= chirp_valid AND mix_valid_1;

  Xfilter_signed <= signed(Xfilter);

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Xfilter_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Xfilter_1 <= Xfilter_signed;
      END IF;
    END IF;
  END PROCESS delayMatch2_process;


  -- Downsample Signal: Downsample by 2, Sample offset 0 
  -- Downsample bypass register
  Downsample_Signal_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Downsample_Signal_bypass_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_1 = '1' THEN
        Downsample_Signal_bypass_reg <= Xfilter_1;
      END IF;
    END IF;
  END PROCESS Downsample_Signal_bypass_process;

  
  Xdown <= Xfilter_1 WHEN enb_1_2_1 = '1' ELSE
      Downsample_Signal_bypass_reg;

  signal_out <= std_logic_vector(Xdown);

  delayMatch3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      LPF_valid_out_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        LPF_valid_out_1 <= LPF_valid_out;
      END IF;
    END IF;
  END PROCESS delayMatch3_process;


  -- Downsample Valid: Downsample by 2, Sample offset 0 
  -- Downsample bypass register
  Downsample_Valid_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Downsample_Valid_bypass_reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_1 = '1' THEN
        Downsample_Valid_bypass_reg <= LPF_valid_out_1;
      END IF;
    END IF;
  END PROCESS Downsample_Valid_bypass_process;

  
  Xdown_1 <= LPF_valid_out_1 WHEN enb_1_2_1 = '1' ELSE
      Downsample_Valid_bypass_reg;

  valid_out <= Xdown_1;

END rtl;

