-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Digital_Spectrometer_from_Chirp_DDC.vhd
-- Created: 2025-12-01 14:00:00
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.66667e-08
-- Target subsystem base rate: 1.66667e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        3.33333e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- avg_out                       ce_out        3.33333e-08
-- avg_valid                     ce_out        3.33333e-08
-- mag_out                       ce_out        3.33333e-08
-- mag_valid                     ce_out        3.33333e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Digital_Spectrometer_from_Chirp_DDC
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC
-- Hierarchy Level: 0
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Digital_Spectrometer_from_Chirp_DDC IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        valid                             :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        avg_out                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
        avg_valid                         :   OUT   std_logic;
        mag_out                           :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        mag_valid                         :   OUT   std_logic
        );
END Digital_Spectrometer_from_Chirp_DDC;


ARCHITECTURE rtl OF Digital_Spectrometer_from_Chirp_DDC IS

  -- Component Declarations
  COMPONENT Digital_Spectrometer_from_Chirp_DDC_tc
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb                             :   OUT   std_logic;
          enb_1_2_0                       :   OUT   std_logic;
          enb_1_2_1                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT DDC
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_2_1                       :   IN    std_logic;
          valid                           :   IN    std_logic;
          signal_out                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Digital_Spectrometer
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          signal_in                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          valid_in                        :   IN    std_logic;
          avg_out                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
          avg_valid                       :   OUT   std_logic;
          mag_out                         :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          mag_valid                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Digital_Spectrometer_from_Chirp_DDC_tc
    USE ENTITY work.Digital_Spectrometer_from_Chirp_DDC_tc(rtl);

  FOR ALL : DDC
    USE ENTITY work.DDC(rtl);

  FOR ALL : Digital_Spectrometer
    USE ENTITY work.Digital_Spectrometer(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL enb_1_2_1                        : std_logic;
  SIGNAL enb_1_2_0                        : std_logic;
  SIGNAL DDC_signal_out                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DDC_valid_out                    : std_logic;
  SIGNAL Digital_Spectrometer_avg_out     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Digital_Spectrometer_avg_valid   : std_logic;
  SIGNAL Digital_Spectrometer_mag_out     : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL Digital_Spectrometer_mag_valid   : std_logic;

BEGIN
  u_Digital_Spectrometer_from_Chirp_DDC_tc : Digital_Spectrometer_from_Chirp_DDC_tc
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              enb => enb,
              enb_1_2_0 => enb_1_2_0,
              enb_1_2_1 => enb_1_2_1
              );

  u_DDC : DDC
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              enb_1_2_1 => enb_1_2_1,
              valid => valid,
              signal_out => DDC_signal_out,  -- sfix16_En15
              valid_out => DDC_valid_out
              );

  u_Digital_Spectrometer : Digital_Spectrometer
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2_0 => enb_1_2_0,
              signal_in => DDC_signal_out,  -- sfix16_En15
              valid_in => DDC_valid_out,
              avg_out => Digital_Spectrometer_avg_out,  -- sfix32_En4
              avg_valid => Digital_Spectrometer_avg_valid,
              mag_out => Digital_Spectrometer_mag_out,  -- sfix26_En15
              mag_valid => Digital_Spectrometer_mag_valid
              );

  ce_out <= enb_1_2_1;

  avg_out <= Digital_Spectrometer_avg_out;

  avg_valid <= Digital_Spectrometer_avg_valid;

  mag_out <= Digital_Spectrometer_mag_out;

  mag_valid <= Digital_Spectrometer_mag_valid;

END rtl;

