###########################################################################
# Auto generated cosimulation 'tclstart' script 
###########################################################################
#  Source Model         : spec_avg_CRD
#  Generated Model      : gm_spec_avg_CRD
#  Cosimulation Model   : gm_spec_avg_CRD_vs
#
#  Source DUT           : gm_spec_avg_CRD_vs/Digital Spectrometer from Chirp DDC
#  Cosimulation DUT     : gm_spec_avg_CRD_vs/Digital Spectrometer from Chirp DDC_vs
#
#  File Location        : hdl_prj\hdlsrc\spec_avg_CRD\gm_spec_avg_CRD_vs.tcl
#  Created              : 2025-12-01 14:00:30
#
#  Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
###########################################################################

###########################################################################
#  ClockName           : clk
#  ResetName           : reset 
#  ClockEnableName     : clk_enable
#
#  ClockLowTime        : 5ns
#  ClockHighTime       : 5ns
#  ClockPeriod         : 10ns
#
#  ResetLength         : 20ns
#  ClockEnableDelay    : 10ns
#  HoldTime            : 2ns
###########################################################################

###########################################################################
#  ModelBaseSampleTime   : 1.66667e-08
#  DutBaseSampleTime     : 1.66667e-08
#  OverClockFactor     : 1
###########################################################################

###########################################################################
#  Mapping of DutBaseSampleTime to ClockPeriod
#
#  N = (ClockPeriod / DutBaseSampleTime) * OverClockFactor
#  1 sec in Simulink corresponds to 6e+08ns in the HDL Simulator(N = 6e+08)
#
###########################################################################

###########################################################################
#  ResetHighAt          : (ClockLowTime + ResetLength + HoldTime)
#  ResetRiseEdge        : 27ns
#  ResetType            : async
#  ResetAssertedLevel   : 1
#
#  ClockEnableHighAt    : (ClockLowTime + ResetLength + ClockEnableDelay + HoldTime)
#  ClockEnableRiseEdge  : 37ns
###########################################################################



exec xvhdl --work work Digital_Spectrometer_from_Chirp_DDC_pkg.vhd Digital_Spectrometer_from_Chirp_DDC_tc.vhd Increment_Real_World.vhd Wrap_To_Zero.vhd Counter_Limited.vhd DitherGen.vhd LookUpTableGen.vhd WaveformGen.vhd NCO1.vhd Chirp.vhd LPF.vhd DitherGen_block.vhd LookUpTableGen_block.vhd WaveformGen_block.vhd LO.vhd DDC.vhd SimpleDualPortRAM_generic.vhd Spectral_Averager.vhd SDFCommutator1.vhd RADIX22FFT_SDF1_1.vhd RADIX22FFT_CTRL1_1.vhd SDFCommutator2.vhd RADIX22FFT_SDF2_2.vhd RADIX22FFT_CTRL1_2.vhd TWDLROM_3_1.vhd Complex4Multiply.vhd SDFCommutator3.vhd RADIX22FFT_SDF1_3.vhd RADIX22FFT_CTRL1_3.vhd SDFCommutator4.vhd RADIX22FFT_SDF2_4.vhd RADIX22FFT_CTRL1_4.vhd TWDLROM_5_1.vhd Complex4Multiply_block.vhd SDFCommutator5.vhd RADIX22FFT_SDF1_5.vhd RADIX22FFT_CTRL1_5.vhd SDFCommutator6.vhd RADIX22FFT_SDF2_6.vhd RADIX22FFT_CTRL1_6.vhd TWDLROM_7_1.vhd Complex4Multiply_block1.vhd SDFCommutator7.vhd RADIX22FFT_SDF1_7.vhd RADIX22FFT_CTRL1_7.vhd SDFCommutator8.vhd RADIX22FFT_SDF2_8.vhd RADIX22FFT_CTRL1_8.vhd TWDLROM_9_1.vhd Complex4Multiply_block2.vhd SDFCommutator9.vhd RADIX22FFT_SDF1_9.vhd RADIX22FFT_CTRL1_1_block.vhd RADIX2FFT_bitNatural.vhd alpha512_pt_FFT.vhd Quadrant_Mapper.vhd CordicKernelMag.vhd CordicKernelMag_block.vhd CordicKernelMag_block1.vhd CordicKernelMag_block2.vhd CordicKernelMag_block3.vhd CordicKernelMag_block4.vhd CordicKernelMag_block5.vhd CordicKernelMag_block6.vhd CordicKernelMag_block7.vhd CordicKernelMag_block8.vhd CordicKernelMag_block9.vhd CordicKernelMag_block10.vhd CordicKernelMag_block11.vhd CordicKernelMag_block12.vhd CordicKernelMag_block13.vhd CordicKernelMag_block14.vhd CordicKernelMag_block15.vhd CordicKernelMag_block16.vhd CordicKernelMag_block17.vhd CordicKernelMag_block18.vhd CordicKernelMag_block19.vhd CordicKernelMag_block20.vhd CordicKernelMag_block21.vhd CordicKernelMag_block22.vhd Digital_Spectrometer.vhd Digital_Spectrometer_from_Chirp_DDC.vhd 
exec xelab Digital_Spectrometer_from_Chirp_DDC --timeprecision_vhdl 1ps --override_timeprecision -dll --snapshot design -debug wave 

cd ../../../

# The xsim.dir must be in PWD
# - save off existing xsim.dir
if {[file exists xsim.dir] == 1} {
    set mtime [file mtime xsim.dir]
    set mtimestamp [clock format $mtime -format %Y%m%d_%H%M%S]
    set xsim_savefile "xsim.dir.$mtimestamp"
    file rename xsim.dir $xsim_savefile
}
# - copy up newly elaborated xsim.dir area from project to the current working directory.
set proj_xsim_dir {hdl_prj\hdlsrc\spec_avg_CRD/xsim.dir}
set proj_mtime [file mtime "$proj_xsim_dir/design"]
file copy -force $proj_xsim_dir .
file mtime xsim.dir $proj_mtime

