open_system('spec_avg_CRD');
open_system('gm_spec_avg_CRD');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 'user2');
annotate_port('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 'user2');
annotate_port('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 'user2');
annotate_port('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 'user2');
annotate_port('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/512 pt FFT', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 'user2');
annotate_port('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 1, 1, 'RAM blocks can be clock-rate pipelined only if it is a RAM System block and ''ModelRAMDelay'' is ''off'' or ''AsyncRead'' is ''on''');
hilite_system('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 'user2');
annotate_port('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 1, 1, 'RAM blocks can be clock-rate pipelined only if it is a RAM System block and ''ModelRAMDelay'' is ''off'' or ''AsyncRead'' is ''on''');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 'user2');
annotate_port('gm_spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 1, 1, 'RAM blocks can be clock-rate pipelined only if it is a RAM System block and ''ModelRAMDelay'' is ''off'' or ''AsyncRead'' is ''on''');
hilite_system('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 'user2');
annotate_port('spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager/Simple Dual Port RAM', 1, 1, 'RAM blocks can be clock-rate pipelined only if it is a RAM System block and ''ModelRAMDelay'' is ''off'' or ''AsyncRead'' is ''on''');
