-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Increment_Real_World.vhd
-- Created: 2025-12-01 13:59:59
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Increment_Real_World
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/DDC/Chirp/Counter Limited/Increment Real World
-- Hierarchy Level: 4
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Increment_Real_World IS
  PORT( u                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END Increment_Real_World;


ARCHITECTURE rtl OF Increment_Real_World IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FixPt_Constant_out1              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FixPt_Sum1_out1                  : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  u_unsigned <= unsigned(u);

  FixPt_Constant_out1 <= to_unsigned(16#0001#, 16);

  FixPt_Sum1_out1 <= u_unsigned + FixPt_Constant_out1;

  y <= std_logic_vector(FixPt_Sum1_out1);

END rtl;

