-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Quadrant_Mapper.vhd
-- Created: 2025-12-01 14:00:00
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Quadrant_Mapper
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/HDL_CMA_core/Quadrant_Mapper
-- Hierarchy Level: 2
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Quadrant_Mapper IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        xin                               :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        yin                               :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        xout                              :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        yout                              :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
        );
END Quadrant_Mapper;


ARCHITECTURE rtl OF Quadrant_Mapper IS

  -- Signals
  SIGNAL xin_signed                       : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL abs1_y                           : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL abs1_cast                        : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL xAbs                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xAbsReg                          : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin_signed                       : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL abs_rsvd_y                       : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL abs_rsvd_cast                    : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL yAbs                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yAbsReg                          : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL XGreaterThanY                    : std_logic;  -- ufix1
  SIGNAL xout_1                           : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout_1                           : signed(25 DOWNTO 0);  -- sfix26_En15

BEGIN
  xin_signed <= signed(xin);

  abs1_cast <= resize(xin_signed, 27);
  
  abs1_y <=  - (abs1_cast) WHEN xin_signed < to_signed(16#0000000#, 26) ELSE
      resize(xin_signed, 27);
  xAbs <= abs1_y(25 DOWNTO 0);

  DelayxAbs_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xAbsReg <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xAbsReg <= xAbs;
      END IF;
    END IF;
  END PROCESS DelayxAbs_process;


  yin_signed <= signed(yin);

  abs_rsvd_cast <= resize(yin_signed, 27);
  
  abs_rsvd_y <=  - (abs_rsvd_cast) WHEN yin_signed < to_signed(16#0000000#, 26) ELSE
      resize(yin_signed, 27);
  yAbs <= abs_rsvd_y(25 DOWNTO 0);

  DelayyAbs_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yAbsReg <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yAbsReg <= yAbs;
      END IF;
    END IF;
  END PROCESS DelayyAbs_process;


  
  XGreaterThanY <= '1' WHEN xAbsReg > yAbsReg ELSE
      '0';

  
  xout_1 <= yAbsReg WHEN XGreaterThanY = '0' ELSE
      xAbsReg;

  xout <= std_logic_vector(xout_1);

  
  yout_1 <= xAbsReg WHEN XGreaterThanY = '0' ELSE
      yAbsReg;

  yout <= std_logic_vector(yout_1);

END rtl;

