-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Wrap_To_Zero.vhd
-- Created: 2025-12-01 13:59:59
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Wrap_To_Zero
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/DDC/Chirp/Counter Limited/Wrap To Zero
-- Hierarchy Level: 4
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Wrap_To_Zero IS
  PORT( U                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END Wrap_To_Zero;


ARCHITECTURE rtl OF Wrap_To_Zero IS

  -- Signals
  SIGNAL U_unsigned                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FixPt_Switch_out1                : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  -- U(k)

  U_unsigned <= unsigned(U);

  
  switch_compare_1 <= '1' WHEN U_unsigned > to_unsigned(16#7530#, 16) ELSE
      '0';

  Constant_out1 <= to_unsigned(16#0000#, 16);

  
  FixPt_Switch_out1 <= U_unsigned WHEN switch_compare_1 = '0' ELSE
      Constant_out1;

  Y <= std_logic_vector(FixPt_Switch_out1);

END rtl;

