-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2_spectrometer_simulink_CRD\Chirp.vhd
-- Created: 2025-12-01 03:44:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Chirp
-- Source Path: lab2_spectrometer_simulink_CRD/Subsystem/Chirp
-- Hierarchy Level: 1
-- Model version: 1.31
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Chirp IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid                             :   IN    std_logic;
        freq_in                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        X                                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        valid_o                           :   OUT   std_logic
        );
END Chirp;


ARCHITECTURE rtl OF Chirp IS

  -- Component Declarations
  COMPONENT NCO1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          inc                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          validIn                         :   IN    std_logic;
          cosine                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : NCO1
    USE ENTITY work.NCO1(rtl);

  -- Signals
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- ufix16_En10
  SIGNAL freq_in_unsigned                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Product_mul_temp                 : unsigned(47 DOWNTO 0);  -- ufix48_En10
  SIGNAL Product_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL NCO1_out1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL NCO1_out2                        : std_logic;

BEGIN
  u_NCO1 : NCO1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              inc => std_logic_vector(Product_out1),  -- uint32
              validIn => valid,
              cosine => NCO1_out1,  -- sfix16_En14
              validOut => NCO1_out2
              );

  Constant_out1 <= to_unsigned(16#98B6#, 16);

  freq_in_unsigned <= unsigned(freq_in);

  Product_mul_temp <= Constant_out1 * freq_in_unsigned;
  Product_out1 <= Product_mul_temp(41 DOWNTO 10);

  X <= NCO1_out1;

  valid_o <= NCO1_out2;

END rtl;

