-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2_spectrometer_simulink_CRD\HDL_CMA_core.vhd
-- Created: 2025-12-01 03:44:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_CMA_core
-- Source Path: lab2_spectrometer_simulink_CRD/Subsystem/HDL_CMA_core
-- Hierarchy Level: 1
-- Model version: 1.31
-- 
-- Complex to Magnitude-Angle
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_CMA_core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In_re                             :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20_En14
        In_im                             :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20_En14
        validIn                           :   IN    std_logic;
        magnitude                         :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        validOut                          :   OUT   std_logic
        );
END HDL_CMA_core;


ARCHITECTURE rtl OF HDL_CMA_core IS

  -- Component Declarations
  COMPONENT Quadrant_Mapper
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          xin                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
          yin                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
          xout                            :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
          yout                            :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En14
          );
  END COMPONENT;

  COMPONENT CordicKernelMag
    PORT( xin                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
          yin                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
          yout                            :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Quadrant_Mapper
    USE ENTITY work.Quadrant_Mapper(rtl);

  FOR ALL : CordicKernelMag
    USE ENTITY work.CordicKernelMag(rtl);

  -- Signals
  SIGNAL Delay_ValidIn_reg                : std_logic_vector(21 DOWNTO 0);  -- ufix1 [22]
  SIGNAL ValidOutDelayed                  : std_logic;
  SIGNAL In_re_signed                     : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL In_im_signed                     : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL qMapReal                         : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL qMapImag                         : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL In1Register                      : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL In2Register                      : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL XQMapped                         : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yQMapped                         : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL XQMapped_signed                  : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yQMapped_signed                  : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin1                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin1                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift1                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout1                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout1                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout1_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout1_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin2                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin2                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift2                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout2                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout2                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout2_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout2_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin3                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin3                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift3                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout3                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout3                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout3_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout3_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin4                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin4                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift4                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout4                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout4                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout4_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout4_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin5                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin5                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift5                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout5                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout5                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout5_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout5_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin6                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin6                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift6                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout6                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout6                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout6_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout6_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin7                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin7                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift7                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout7                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout7                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout7_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout7_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin8                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin8                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift8                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout8                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout8                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout8_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout8_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin9                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin9                             : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift9                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout9                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout9                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout9_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout9_signed                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin10                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin10                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift10                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout10                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout10                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout10_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout10_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin11                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin11                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift11                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout11                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout11                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout11_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout11_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin12                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin12                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift12                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout12                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout12                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout12_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout12_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin13                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin13                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift13                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout13                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout13                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout13_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout13_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin14                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin14                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift14                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout14                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout14                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout14_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout14_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin15                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin15                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift15                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout15                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout15                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout15_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout15_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin16                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin16                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift16                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout16                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout16                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout16_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout16_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin17                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin17                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift17                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout17                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout17                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout17_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout17_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin18                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin18                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift18                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout18                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout18                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout18_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yout18_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin19                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL yin19                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL shift19                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout19                           : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL yout19deadOut                    : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout19_signed                    : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL reset_outval                     : std_logic;
  SIGNAL xin20                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL CSD_Gain_Factor_mul_temp         : signed(36 DOWNTO 0);  -- sfix37_En29
  SIGNAL CSD_Gain_Factor_cast             : signed(35 DOWNTO 0);  -- sfix36_En29
  SIGNAL xoutscaled                       : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL zeroC                            : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL outSwitchMag                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL xin21                            : signed(20 DOWNTO 0);  -- sfix21_En14

BEGIN
  u_QuadrantMapper : Quadrant_Mapper
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              xin => std_logic_vector(In1Register),  -- sfix21_En14
              yin => std_logic_vector(In2Register),  -- sfix21_En14
              xout => XQMapped,  -- sfix21_En14
              yout => yQMapped  -- sfix21_En14
              );

  u_Iteration : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin1),  -- sfix21_En14
              yin => std_logic_vector(yin1),  -- sfix21_En14
              idx => std_logic_vector(shift1),  -- ufix6
              xout => xout1,  -- sfix21_En14
              yout => yout1  -- sfix21_En14
              );

  u_Iteration_1 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin2),  -- sfix21_En14
              yin => std_logic_vector(yin2),  -- sfix21_En14
              idx => std_logic_vector(shift2),  -- ufix6
              xout => xout2,  -- sfix21_En14
              yout => yout2  -- sfix21_En14
              );

  u_Iteration_2 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin3),  -- sfix21_En14
              yin => std_logic_vector(yin3),  -- sfix21_En14
              idx => std_logic_vector(shift3),  -- ufix6
              xout => xout3,  -- sfix21_En14
              yout => yout3  -- sfix21_En14
              );

  u_Iteration_3 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin4),  -- sfix21_En14
              yin => std_logic_vector(yin4),  -- sfix21_En14
              idx => std_logic_vector(shift4),  -- ufix6
              xout => xout4,  -- sfix21_En14
              yout => yout4  -- sfix21_En14
              );

  u_Iteration_4 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin5),  -- sfix21_En14
              yin => std_logic_vector(yin5),  -- sfix21_En14
              idx => std_logic_vector(shift5),  -- ufix6
              xout => xout5,  -- sfix21_En14
              yout => yout5  -- sfix21_En14
              );

  u_Iteration_5 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin6),  -- sfix21_En14
              yin => std_logic_vector(yin6),  -- sfix21_En14
              idx => std_logic_vector(shift6),  -- ufix6
              xout => xout6,  -- sfix21_En14
              yout => yout6  -- sfix21_En14
              );

  u_Iteration_6 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin7),  -- sfix21_En14
              yin => std_logic_vector(yin7),  -- sfix21_En14
              idx => std_logic_vector(shift7),  -- ufix6
              xout => xout7,  -- sfix21_En14
              yout => yout7  -- sfix21_En14
              );

  u_Iteration_7 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin8),  -- sfix21_En14
              yin => std_logic_vector(yin8),  -- sfix21_En14
              idx => std_logic_vector(shift8),  -- ufix6
              xout => xout8,  -- sfix21_En14
              yout => yout8  -- sfix21_En14
              );

  u_Iteration_8 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin9),  -- sfix21_En14
              yin => std_logic_vector(yin9),  -- sfix21_En14
              idx => std_logic_vector(shift9),  -- ufix6
              xout => xout9,  -- sfix21_En14
              yout => yout9  -- sfix21_En14
              );

  u_Iteration_9 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin10),  -- sfix21_En14
              yin => std_logic_vector(yin10),  -- sfix21_En14
              idx => std_logic_vector(shift10),  -- ufix6
              xout => xout10,  -- sfix21_En14
              yout => yout10  -- sfix21_En14
              );

  u_Iteration_10 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin11),  -- sfix21_En14
              yin => std_logic_vector(yin11),  -- sfix21_En14
              idx => std_logic_vector(shift11),  -- ufix6
              xout => xout11,  -- sfix21_En14
              yout => yout11  -- sfix21_En14
              );

  u_Iteration_11 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin12),  -- sfix21_En14
              yin => std_logic_vector(yin12),  -- sfix21_En14
              idx => std_logic_vector(shift12),  -- ufix6
              xout => xout12,  -- sfix21_En14
              yout => yout12  -- sfix21_En14
              );

  u_Iteration_12 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin13),  -- sfix21_En14
              yin => std_logic_vector(yin13),  -- sfix21_En14
              idx => std_logic_vector(shift13),  -- ufix6
              xout => xout13,  -- sfix21_En14
              yout => yout13  -- sfix21_En14
              );

  u_Iteration_13 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin14),  -- sfix21_En14
              yin => std_logic_vector(yin14),  -- sfix21_En14
              idx => std_logic_vector(shift14),  -- ufix6
              xout => xout14,  -- sfix21_En14
              yout => yout14  -- sfix21_En14
              );

  u_Iteration_14 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin15),  -- sfix21_En14
              yin => std_logic_vector(yin15),  -- sfix21_En14
              idx => std_logic_vector(shift15),  -- ufix6
              xout => xout15,  -- sfix21_En14
              yout => yout15  -- sfix21_En14
              );

  u_Iteration_15 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin16),  -- sfix21_En14
              yin => std_logic_vector(yin16),  -- sfix21_En14
              idx => std_logic_vector(shift16),  -- ufix6
              xout => xout16,  -- sfix21_En14
              yout => yout16  -- sfix21_En14
              );

  u_Iteration_16 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin17),  -- sfix21_En14
              yin => std_logic_vector(yin17),  -- sfix21_En14
              idx => std_logic_vector(shift17),  -- ufix6
              xout => xout17,  -- sfix21_En14
              yout => yout17  -- sfix21_En14
              );

  u_Iteration_17 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin18),  -- sfix21_En14
              yin => std_logic_vector(yin18),  -- sfix21_En14
              idx => std_logic_vector(shift18),  -- ufix6
              xout => xout18,  -- sfix21_En14
              yout => yout18  -- sfix21_En14
              );

  u_Iteration_18 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin19),  -- sfix21_En14
              yin => std_logic_vector(yin19),  -- sfix21_En14
              idx => std_logic_vector(shift19),  -- ufix6
              xout => xout19,  -- sfix21_En14
              yout => yout19deadOut  -- sfix21_En14
              );

  Delay_ValidIn_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_ValidIn_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_ValidIn_reg(0) <= validIn;
        Delay_ValidIn_reg(21 DOWNTO 1) <= Delay_ValidIn_reg(20 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay_ValidIn_process;

  ValidOutDelayed <= Delay_ValidIn_reg(21);

  In_re_signed <= signed(In_re);

  qMapReal <= resize(In_re_signed, 21);

  In_im_signed <= signed(In_im);

  qMapImag <= resize(In_im_signed, 21);

  DelayRealInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In1Register <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In1Register <= qMapReal;
      END IF;
    END IF;
  END PROCESS DelayRealInput_process;


  DelayImagInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In2Register <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In2Register <= qMapImag;
      END IF;
    END IF;
  END PROCESS DelayImagInput_process;


  XQMapped_signed <= signed(XQMapped);

  yQMapped_signed <= signed(yQMapped);

  DelayQuadMapper1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin1 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin1 <= XQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper1_process;


  DelayQuadMapper2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin1 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin1 <= yQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper2_process;


  shift1 <= to_unsigned(16#01#, 6);

  xout1_signed <= signed(xout1);

  yout1_signed <= signed(yout1);

  Pipeline1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin2 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin2 <= xout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_process;


  Pipeline1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin2 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin2 <= yout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_1_process;


  shift2 <= to_unsigned(16#02#, 6);

  xout2_signed <= signed(xout2);

  yout2_signed <= signed(yout2);

  Pipeline2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin3 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin3 <= xout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_process;


  Pipeline2_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin3 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin3 <= yout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_1_process;


  shift3 <= to_unsigned(16#03#, 6);

  xout3_signed <= signed(xout3);

  yout3_signed <= signed(yout3);

  Pipeline3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin4 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin4 <= xout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_process;


  Pipeline3_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin4 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin4 <= yout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_1_process;


  shift4 <= to_unsigned(16#04#, 6);

  xout4_signed <= signed(xout4);

  yout4_signed <= signed(yout4);

  Pipeline4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin5 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin5 <= xout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_process;


  Pipeline4_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin5 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin5 <= yout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_1_process;


  shift5 <= to_unsigned(16#05#, 6);

  xout5_signed <= signed(xout5);

  yout5_signed <= signed(yout5);

  Pipeline5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin6 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin6 <= xout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_process;


  Pipeline5_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin6 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin6 <= yout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_1_process;


  shift6 <= to_unsigned(16#06#, 6);

  xout6_signed <= signed(xout6);

  yout6_signed <= signed(yout6);

  Pipeline6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin7 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin7 <= xout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_process;


  Pipeline6_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin7 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin7 <= yout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_1_process;


  shift7 <= to_unsigned(16#07#, 6);

  xout7_signed <= signed(xout7);

  yout7_signed <= signed(yout7);

  Pipeline7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin8 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin8 <= xout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_process;


  Pipeline7_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin8 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin8 <= yout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_1_process;


  shift8 <= to_unsigned(16#08#, 6);

  xout8_signed <= signed(xout8);

  yout8_signed <= signed(yout8);

  Pipeline8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin9 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin9 <= xout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_process;


  Pipeline8_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin9 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin9 <= yout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_1_process;


  shift9 <= to_unsigned(16#09#, 6);

  xout9_signed <= signed(xout9);

  yout9_signed <= signed(yout9);

  Pipeline9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin10 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin10 <= xout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_process;


  Pipeline9_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin10 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin10 <= yout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_1_process;


  shift10 <= to_unsigned(16#0A#, 6);

  xout10_signed <= signed(xout10);

  yout10_signed <= signed(yout10);

  Pipeline10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin11 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin11 <= xout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_process;


  Pipeline10_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin11 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin11 <= yout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_1_process;


  shift11 <= to_unsigned(16#0B#, 6);

  xout11_signed <= signed(xout11);

  yout11_signed <= signed(yout11);

  Pipeline11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin12 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin12 <= xout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_process;


  Pipeline11_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin12 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin12 <= yout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_1_process;


  shift12 <= to_unsigned(16#0C#, 6);

  xout12_signed <= signed(xout12);

  yout12_signed <= signed(yout12);

  Pipeline12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin13 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin13 <= xout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_process;


  Pipeline12_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin13 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin13 <= yout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_1_process;


  shift13 <= to_unsigned(16#0D#, 6);

  xout13_signed <= signed(xout13);

  yout13_signed <= signed(yout13);

  Pipeline13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin14 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin14 <= xout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_process;


  Pipeline13_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin14 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin14 <= yout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_1_process;


  shift14 <= to_unsigned(16#0E#, 6);

  xout14_signed <= signed(xout14);

  yout14_signed <= signed(yout14);

  Pipeline14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin15 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin15 <= xout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_process;


  Pipeline14_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin15 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin15 <= yout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_1_process;


  shift15 <= to_unsigned(16#0F#, 6);

  xout15_signed <= signed(xout15);

  yout15_signed <= signed(yout15);

  Pipeline15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin16 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin16 <= xout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline15_process;


  Pipeline15_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin16 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin16 <= yout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline15_1_process;


  shift16 <= to_unsigned(16#10#, 6);

  xout16_signed <= signed(xout16);

  yout16_signed <= signed(yout16);

  Pipeline16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin17 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin17 <= xout16_signed;
      END IF;
    END IF;
  END PROCESS Pipeline16_process;


  Pipeline16_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin17 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin17 <= yout16_signed;
      END IF;
    END IF;
  END PROCESS Pipeline16_1_process;


  shift17 <= to_unsigned(16#11#, 6);

  xout17_signed <= signed(xout17);

  yout17_signed <= signed(yout17);

  Pipeline17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin18 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin18 <= xout17_signed;
      END IF;
    END IF;
  END PROCESS Pipeline17_process;


  Pipeline17_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin18 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin18 <= yout17_signed;
      END IF;
    END IF;
  END PROCESS Pipeline17_1_process;


  shift18 <= to_unsigned(16#12#, 6);

  xout18_signed <= signed(xout18);

  yout18_signed <= signed(yout18);

  Pipeline18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin19 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin19 <= xout18_signed;
      END IF;
    END IF;
  END PROCESS Pipeline18_process;


  Pipeline18_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin19 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin19 <= yout18_signed;
      END IF;
    END IF;
  END PROCESS Pipeline18_1_process;


  shift19 <= to_unsigned(16#13#, 6);

  xout19_signed <= signed(xout19);

  reset_outval <=  NOT ValidOutDelayed;

  Pipeline19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin20 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin20 <= xout19_signed;
      END IF;
    END IF;
  END PROCESS Pipeline19_process;


  -- CSD Encoding (28141) : 1001'001'00001'01'01; Cost (Adders) = 5
  CSD_Gain_Factor_mul_temp <= ((((resize(xin20 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 37) - resize(xin20 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 37)) - resize(xin20 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 37)) - resize(xin20 & '0' & '0' & '0' & '0', 37)) - resize(xin20 & '0' & '0', 37)) + resize(xin20, 37);
  CSD_Gain_Factor_cast <= CSD_Gain_Factor_mul_temp(35 DOWNTO 0);
  xoutscaled <= CSD_Gain_Factor_cast(35 DOWNTO 15);

  zeroC <= to_signed(16#000000#, 21);

  
  outSwitchMag <= xoutscaled WHEN reset_outval = '0' ELSE
      zeroC;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin21 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin21 <= outSwitchMag;
      END IF;
    END IF;
  END PROCESS Output_Register_process;


  magnitude <= std_logic_vector(xin21);

  DelayValidOut_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validOut <= ValidOutDelayed;
      END IF;
    END IF;
  END PROCESS DelayValidOut_process;


END rtl;

