-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2_spectrometer_simulink_CRD\lab2_spectrometer_simulink_CRD.vhd
-- Created: 2025-12-01 03:25:56
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 4.44444e-09
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: lab2_spectrometer_simulink_CRD
-- Source Path: lab2_spectrometer_simulink_CRD
-- Hierarchy Level: 0
-- Model version: 1.26
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY lab2_spectrometer_simulink_CRD IS
END lab2_spectrometer_simulink_CRD;


ARCHITECTURE rtl OF lab2_spectrometer_simulink_CRD IS

BEGIN
  -- All logic inside the DUT 'lab2_spectrometer_simulink_CRD' was detected to be redundant by HDL Coder. Consider connecting 
  -- output ports to the design in order to preserve logic for code generation

END rtl;

