-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2_spectrometer_simulink_CRD\Subsystem.vhd
-- Created: 2025-12-01 03:44:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 4.44444e-09
-- Target subsystem base rate: 4.44444e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        4.44444e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- mag_out                       ce_out        4.44444e-09
-- valid_out                     ce_out        4.44444e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: lab2_spectrometer_simulink_CRD/Subsystem
-- Hierarchy Level: 0
-- Model version: 1.31
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        valid                             :   IN    std_logic;
        freq_in                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ce_out                            :   OUT   std_logic;
        mag_out                           :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        valid_out                         :   OUT   std_logic
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Component Declarations
  COMPONENT Chirp
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          valid                           :   IN    std_logic;
          freq_in                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          X                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          valid_o                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20_En14
          dataOut_im                      :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT HDL_CMA_core
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_re                           :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20_En14
          In_im                           :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20_En14
          validIn                         :   IN    std_logic;
          magnitude                       :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Chirp
    USE ENTITY work.Chirp(rtl);

  FOR ALL : FFT
    USE ENTITY work.FFT(rtl);

  FOR ALL : HDL_CMA_core
    USE ENTITY work.HDL_CMA_core(rtl);

  -- Signals
  SIGNAL X                                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Chirp_valid_o                    : std_logic;
  SIGNAL FFT_out1_re                      : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL FFT_out1_im                      : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL FFT_out2                         : std_logic;
  SIGNAL Complex_to_Magnitude_Angle_out1  : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL Complex_to_Magnitude_Angle_out2  : std_logic;

BEGIN
  u_Chirp : Chirp
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              valid => valid,
              freq_in => freq_in,  -- uint32
              X => X,  -- sfix16_En14
              valid_o => Chirp_valid_o
              );

  u_FFT : FFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => X,  -- sfix16_En14
              validIn => Chirp_valid_o,
              dataOut_re => FFT_out1_re,  -- sfix20_En14
              dataOut_im => FFT_out1_im,  -- sfix20_En14
              validOut => FFT_out2
              );

  u_Complex_to_Magnitude_Angle : HDL_CMA_core
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In_re => FFT_out1_re,  -- sfix20_En14
              In_im => FFT_out1_im,  -- sfix20_En14
              validIn => FFT_out2,
              magnitude => Complex_to_Magnitude_Angle_out1,  -- sfix21_En14
              validOut => Complex_to_Magnitude_Angle_out2
              );

  ce_out <= clk_enable;

  mag_out <= Complex_to_Magnitude_Angle_out1;

  valid_out <= Complex_to_Magnitude_Angle_out2;

END rtl;

