-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ddc_simulink_CRD_fixed\Counter_Limited.vhd
-- Created: 2025-11-17 12:04:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Counter_Limited
-- Source Path: ddc_simulink_CRD_fixed/Chirp/Counter Limited
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Counter_Limited IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END Counter_Limited;


ARCHITECTURE rtl OF Counter_Limited IS

  -- Component Declarations
  COMPONENT Increment_Real_World
    PORT( u                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          y                               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT Wrap_To_Zero
    PORT( U                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Y                               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Increment_Real_World
    USE ENTITY work.Increment_Real_World(rtl);

  FOR ALL : Wrap_To_Zero
    USE ENTITY work.Wrap_To_Zero(rtl);

  -- Signals
  SIGNAL Output_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Increment_Real_World_out1        : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Wrap_To_Zero_out1                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Wrap_To_Zero_out1_unsigned       : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_Increment_Real_World : Increment_Real_World
    PORT MAP( u => std_logic_vector(Output_out1),  -- uint8
              y => Increment_Real_World_out1  -- uint8
              );

  u_Wrap_To_Zero : Wrap_To_Zero
    PORT MAP( U => Increment_Real_World_out1,  -- uint8
              Y => Wrap_To_Zero_out1  -- uint8
              );

  Wrap_To_Zero_out1_unsigned <= unsigned(Wrap_To_Zero_out1);

  Output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Output_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Output_out1 <= Wrap_To_Zero_out1_unsigned;
      END IF;
    END IF;
  END PROCESS Output_process;


  y <= std_logic_vector(Output_out1);

END rtl;

