-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ddc_simulink_CRD_fixed\ddc_simulink_CRD_fixed.vhd
-- Created: 2025-11-17 12:04:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.66667e-08
-- Target subsystem base rate: 1.66667e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        3.33333e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        3.33333e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ddc_simulink_CRD_fixed
-- Source Path: ddc_simulink_CRD_fixed
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ddc_simulink_CRD_fixed IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En16
        );
END ddc_simulink_CRD_fixed;


ARCHITECTURE rtl OF ddc_simulink_CRD_fixed IS

  -- Component Declarations
  COMPONENT ddc_simulink_CRD_fixed_tc
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb                             :   OUT   std_logic;
          enb_1_2_1                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Chirp
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          valid                           :   IN    std_logic;
          X                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT NCO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          validIn                         :   IN    std_logic;
          cosine                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT LPF
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ddc_simulink_CRD_fixed_tc
    USE ENTITY work.ddc_simulink_CRD_fixed_tc(rtl);

  FOR ALL : Chirp
    USE ENTITY work.Chirp(rtl);

  FOR ALL : NCO
    USE ENTITY work.NCO(rtl);

  FOR ALL : LPF
    USE ENTITY work.LPF(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL enb_1_2_1                        : std_logic;
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL X                                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL X_signed                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL NCO_out1                         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL NCO_out1_signed                  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL NCO_out1_1                       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Product_mul_temp                 : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Xmix                             : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Xfilter                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Xfilter_signed                   : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Xfilter_1                        : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Downsample_bypass_reg            : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Xdown                            : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Xdown_1                          : signed(15 DOWNTO 0);  -- sfix16_En16

BEGIN
  u_ddc_simulink_CRD_fixed_tc : ddc_simulink_CRD_fixed_tc
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              enb => enb,
              enb_1_2_1 => enb_1_2_1
              );

  u_Chirp : Chirp
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              valid => Constant_out1,
              X => X  -- sfix16_En14
              );

  u_NCO : NCO
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              validIn => Constant_out1,
              cosine => NCO_out1  -- sfix16_En14
              );

  u_LPF : LPF
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => std_logic_vector(Xmix),  -- sfix16_En14
              Out1 => Xfilter  -- sfix16_En16
              );

  Constant_out1 <= '1';

  X_signed <= signed(X);

  NCO_out1_signed <= signed(NCO_out1);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      NCO_out1_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        NCO_out1_1 <= NCO_out1_signed;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  Product_mul_temp <= X_signed * NCO_out1_1;
  Xmix <= Product_mul_temp(29 DOWNTO 14);

  Xfilter_signed <= signed(Xfilter);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Xfilter_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Xfilter_1 <= Xfilter_signed;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  -- Downsample: Downsample by 2, Sample offset 0 
  -- Downsample bypass register
  Downsample_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Downsample_bypass_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_1 = '1' THEN
        Downsample_bypass_reg <= Xfilter_1;
      END IF;
    END IF;
  END PROCESS Downsample_bypass_process;

  
  Xdown <= Xfilter_1 WHEN enb_1_2_1 = '1' ELSE
      Downsample_bypass_reg;

  Xdown_1 <= Xdown;

  Out1 <= std_logic_vector(Xdown_1);

  ce_out <= enb_1_2_1;

END rtl;

