-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\CordicKernelMag_block21.vhd
-- Created: 2025-12-01 13:50:44
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CordicKernelMag_block21
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Magnitude
-- Hierarchy Level: 2
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CordicKernelMag_block21 IS
  PORT( xin                               :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        yin                               :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        idx                               :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        xout                              :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        yout                              :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
        );
END CordicKernelMag_block21;


ARCHITECTURE rtl OF CordicKernelMag_block21 IS

  -- Signals
  SIGNAL yin_signed                       : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yLessThanZero                    : std_logic;
  SIGNAL xin_signed                       : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL idx_unsigned                     : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL dynamic_shift1_cast              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL yShifted                         : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xout2                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xout1                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xout_tmp                         : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL dynamic_shift_cast               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL xShifted                         : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout2                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout1                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout_tmp                         : signed(25 DOWNTO 0);  -- sfix26_En15

BEGIN
  yin_signed <= signed(yin);

  
  yLessThanZero <= '1' WHEN yin_signed < to_signed(16#0000000#, 26) ELSE
      '0';

  xin_signed <= signed(xin);

  idx_unsigned <= unsigned(idx);

  dynamic_shift1_cast <= resize(idx_unsigned, 8);
  yShifted <= SHIFT_RIGHT(yin_signed, to_integer(dynamic_shift1_cast));

  xout2 <= xin_signed + yShifted;

  xout1 <= xin_signed - yShifted;

  
  xout_tmp <= xout2 WHEN yLessThanZero = '0' ELSE
      xout1;

  xout <= std_logic_vector(xout_tmp);

  dynamic_shift_cast <= resize(idx_unsigned, 8);
  xShifted <= SHIFT_RIGHT(xin_signed, to_integer(dynamic_shift_cast));

  yout2 <= yin_signed - xShifted;

  yout1 <= yin_signed + xShifted;

  
  yout_tmp <= yout2 WHEN yLessThanZero = '0' ELSE
      yout1;

  yout <= std_logic_vector(yout_tmp);

END rtl;

