-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Counter_Limited.vhd
-- Created: 2025-12-01 13:50:43
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Counter_Limited
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/DDC/Chirp/Counter Limited
-- Hierarchy Level: 3
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Counter_Limited IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END Counter_Limited;


ARCHITECTURE rtl OF Counter_Limited IS

  -- Component Declarations
  COMPONENT Increment_Real_World
    PORT( u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          y                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT Wrap_To_Zero
    PORT( U                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Y                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Increment_Real_World
    USE ENTITY work.Increment_Real_World(rtl);

  FOR ALL : Wrap_To_Zero
    USE ENTITY work.Wrap_To_Zero(rtl);

  -- Signals
  SIGNAL Output_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Increment_Real_World_y           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Wrap_To_Zero_Y                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Wrap_To_Zero_Y_unsigned          : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  u_Increment_Real_World : Increment_Real_World
    PORT MAP( u => std_logic_vector(Output_out1),  -- uint16
              y => Increment_Real_World_y  -- uint16
              );

  u_Wrap_To_Zero : Wrap_To_Zero
    PORT MAP( U => Increment_Real_World_y,  -- uint16
              Y => Wrap_To_Zero_Y  -- uint16
              );

  Wrap_To_Zero_Y_unsigned <= unsigned(Wrap_To_Zero_Y);

  Output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Output_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Output_out1 <= Wrap_To_Zero_Y_unsigned;
      END IF;
    END IF;
  END PROCESS Output_process;


  y <= std_logic_vector(Output_out1);

END rtl;

