-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\ddc_spec_avg_tb.vhd
-- Created: 2025-12-01 12:25:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.66667e-08
-- Target subsystem base rate: 1.66667e-08
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ddc_spec_avg_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
LIBRARY work;
USE work.ddc_spec_avg_pkg.ALL;
USE work.ddc_spec_avg_tb_pkg.ALL;

ENTITY ddc_spec_avg_tb IS
END ddc_spec_avg_tb;


ARCHITECTURE rtl OF ddc_spec_avg_tb IS

  -- Component Declarations
  COMPONENT ddc_spec_avg
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          valid                           :   IN    std_logic;
          ce_out                          :   OUT   std_logic;
          avg_out                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
          valid_out                       :   OUT   std_logic;
          sample_in                       :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          valid_in                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ddc_spec_avg
    USE ENTITY work.ddc_spec_avg(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL rawData_valid                    : std_logic;
  SIGNAL valid_in_done                    : std_logic;  -- ufix1
  SIGNAL ce_out                           : std_logic;
  SIGNAL valid_in_done_enb                : std_logic;  -- ufix1
  SIGNAL avg_out_addr                     : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL valid_in_lastAddr                : std_logic;  -- ufix1
  SIGNAL resetn                           : std_logic;
  SIGNAL check4_done                      : std_logic;  -- ufix1
  SIGNAL sample_in_done                   : std_logic;  -- ufix1
  SIGNAL sample_in_done_enb               : std_logic;  -- ufix1
  SIGNAL sample_in_lastAddr               : std_logic;  -- ufix1
  SIGNAL check3_done                      : std_logic;  -- ufix1
  SIGNAL valid_out_done                   : std_logic;  -- ufix1
  SIGNAL valid_out_done_enb               : std_logic;  -- ufix1
  SIGNAL valid_out_lastAddr               : std_logic;  -- ufix1
  SIGNAL check2_done                      : std_logic;  -- ufix1
  SIGNAL avg_out_done                     : std_logic;  -- ufix1
  SIGNAL avg_out_done_enb                 : std_logic;  -- ufix1
  SIGNAL avg_out_active                   : std_logic;  -- ufix1
  SIGNAL holdData_valid                   : std_logic;
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL valid_offset                     : std_logic;
  SIGNAL valid_1                          : std_logic;
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL notDone                          : std_logic;
  SIGNAL avg_out                          : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL valid_out                        : std_logic;
  SIGNAL sample_in                        : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL valid_in                         : std_logic;
  SIGNAL avg_out_enb                      : std_logic;  -- ufix1
  SIGNAL avg_out_lastAddr                 : std_logic;  -- ufix1
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL avg_out_signed                   : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_addr_delay_1             : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL avg_out_expected                 : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_ref_hold                 : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_ref                      : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_testFailure              : std_logic;  -- ufix1
  SIGNAL valid_out_addr_delay_1           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL valid_out_expected               : std_logic;
  SIGNAL valid_out_ref_hold               : std_logic;
  SIGNAL valid_out_ref                    : std_logic;
  SIGNAL valid_out_testFailure            : std_logic;  -- ufix1
  SIGNAL sample_in_signed                 : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL sample_in_addr_delay_1           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL sample_in_expected               : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL sample_in_ref_hold               : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL sample_in_ref                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL sample_in_testFailure            : std_logic;  -- ufix1
  SIGNAL valid_in_addr_delay_1            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL valid_in_expected                : std_logic;
  SIGNAL valid_in_ref_hold                : std_logic;
  SIGNAL valid_in_ref                     : std_logic;
  SIGNAL valid_in_testFailure             : std_logic;  -- ufix1
  SIGNAL testFailure                      : std_logic;  -- ufix1

BEGIN
  u_ddc_spec_avg : ddc_spec_avg
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              valid => valid_1,
              ce_out => ce_out,
              avg_out => avg_out,  -- sfix32_En4
              valid_out => valid_out,
              sample_in => sample_in,  -- sfix26_En15
              valid_in => valid_in
              );

  -- Data source for valid
  rawData_valid <= '1';

  valid_in_done_enb <= valid_in_done AND ce_out;

  
  valid_in_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  valid_in_done <= valid_in_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_4_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check4_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF valid_in_done_enb = '1' THEN
        check4_done <= valid_in_done;
      END IF;
    END IF;
  END PROCESS checkDone_4_process;

  sample_in_done_enb <= sample_in_done AND ce_out;

  
  sample_in_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  sample_in_done <= sample_in_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_3_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check3_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF sample_in_done_enb = '1' THEN
        check3_done <= sample_in_done;
      END IF;
    END IF;
  END PROCESS checkDone_3_process;

  valid_out_done_enb <= valid_out_done AND ce_out;

  
  valid_out_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  valid_out_done <= valid_out_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_2_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check2_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF valid_out_done_enb = '1' THEN
        check2_done <= valid_out_done;
      END IF;
    END IF;
  END PROCESS checkDone_2_process;

  avg_out_done_enb <= avg_out_done AND ce_out;

  
  avg_out_active <= '1' WHEN avg_out_addr /= to_unsigned(16#3A98#, 14) ELSE
      '0';

  -- holdData reg for Constant_out1
  stimuli_Constant_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_valid <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_valid <= rawData_valid;
    END IF;
  END PROCESS stimuli_Constant_out1_process;

  stimuli_Constant_out1_1: PROCESS (rawData_valid, tb_enb_delay)
  BEGIN
    IF tb_enb_delay = '0' THEN
      valid_offset <= holdData_valid;
    ELSE
      valid_offset <= rawData_valid;
    END IF;
  END PROCESS stimuli_Constant_out1_1;

  valid_1 <= valid_offset AFTER 2 ns;

  snkDonen <=  NOT snkDone;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;


  notDone <= tb_enb_delay AND snkDonen;

  clk_enable <= notDone AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  avg_out_enb <= ce_out AND avg_out_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 15000
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_out_addr <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF avg_out_enb = '1' THEN
        IF avg_out_addr >= to_unsigned(16#3A98#, 14) THEN 
          avg_out_addr <= to_unsigned(16#0000#, 14);
        ELSE 
          avg_out_addr <= avg_out_addr + to_unsigned(16#0001#, 14);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  avg_out_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  avg_out_done <= avg_out_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF avg_out_done_enb = '1' THEN
        check1_done <= avg_out_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  snkDone <= check4_done AND (check3_done AND (check1_done AND check2_done));

  avg_out_signed <= signed(avg_out);

  avg_out_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for avg_out_expected
  avg_out_expected_fileread: PROCESS (avg_out_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "avg_out_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(31 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    avg_out_expected <= signed(read_data(31 DOWNTO 0));
  END PROCESS avg_out_expected_fileread;

  -- Bypass register to hold avg_out_ref
  DataHold_avg_out_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_out_ref_hold <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        avg_out_ref_hold <= avg_out_expected;
      END IF;
    END IF;
  END PROCESS DataHold_avg_out_ref_process;

  
  avg_out_ref <= avg_out_ref_hold WHEN ce_out = '0' ELSE
      avg_out_expected;

  avg_out_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_out_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND avg_out_signed /= avg_out_ref THEN
        avg_out_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in avg_out_signed: Expected " & to_hex(avg_out_ref) & (" Actual " & to_hex(avg_out_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS avg_out_signed_checker;

  valid_out_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for valid_out_expected
  valid_out_expected_fileread: PROCESS (valid_out_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "valid_out_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic;

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      READ(l, read_data);
    END IF;
    valid_out_expected <= read_data;
  END PROCESS valid_out_expected_fileread;

  -- Bypass register to hold valid_out_ref
  DataHold_valid_out_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      valid_out_ref_hold <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        valid_out_ref_hold <= valid_out_expected;
      END IF;
    END IF;
  END PROCESS DataHold_valid_out_ref_process;

  
  valid_out_ref <= valid_out_ref_hold WHEN ce_out = '0' ELSE
      valid_out_expected;

  valid_out_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      valid_out_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND valid_out /= valid_out_ref THEN
        valid_out_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in valid_out: Expected " & to_hex(valid_out_ref) & (" Actual " & to_hex(valid_out))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS valid_out_checker;

  sample_in_signed <= signed(sample_in);

  sample_in_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for sample_in_expected
  sample_in_expected_fileread: PROCESS (sample_in_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "sample_in_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(27 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    sample_in_expected <= signed(read_data(25 DOWNTO 0));
  END PROCESS sample_in_expected_fileread;

  -- Bypass register to hold sample_in_ref
  DataHold_sample_in_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sample_in_ref_hold <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        sample_in_ref_hold <= sample_in_expected;
      END IF;
    END IF;
  END PROCESS DataHold_sample_in_ref_process;

  
  sample_in_ref <= sample_in_ref_hold WHEN ce_out = '0' ELSE
      sample_in_expected;

  sample_in_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sample_in_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND sample_in_signed /= sample_in_ref THEN
        sample_in_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in sample_in_signed: Expected " & to_hex(sample_in_ref) & (" Actual " & to_hex(sample_in_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS sample_in_signed_checker;

  valid_in_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for valid_in_expected
  valid_in_expected_fileread: PROCESS (valid_in_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "valid_in_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic;

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      READ(l, read_data);
    END IF;
    valid_in_expected <= read_data;
  END PROCESS valid_in_expected_fileread;

  -- Bypass register to hold valid_in_ref
  DataHold_valid_in_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      valid_in_ref_hold <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        valid_in_ref_hold <= valid_in_expected;
      END IF;
    END IF;
  END PROCESS DataHold_valid_in_ref_process;

  
  valid_in_ref <= valid_in_ref_hold WHEN ce_out = '0' ELSE
      valid_in_expected;

  valid_in_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      valid_in_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND valid_in /= valid_in_ref THEN
        valid_in_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in valid_in: Expected " & to_hex(valid_in_ref) & (" Actual " & to_hex(valid_in))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS valid_in_checker;

  testFailure <= valid_in_testFailure OR (sample_in_testFailure OR (avg_out_testFailure OR valid_out_testFailure));

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

