-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Digital_Spectrometer_from_Chirp_DDC_tb.vhd
-- Created: 2025-12-01 13:51:20
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.66667e-08
-- Target subsystem base rate: 1.66667e-08
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Digital_Spectrometer_from_Chirp_DDC_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
LIBRARY work;
USE work.Digital_Spectrometer_from_Chirp_DDC_pkg.ALL;
USE work.Digital_Spectrometer_from_Chirp_DDC_tb_pkg.ALL;

ENTITY Digital_Spectrometer_from_Chirp_DDC_tb IS
END Digital_Spectrometer_from_Chirp_DDC_tb;


ARCHITECTURE rtl OF Digital_Spectrometer_from_Chirp_DDC_tb IS

  -- Component Declarations
  COMPONENT Digital_Spectrometer_from_Chirp_DDC
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          valid                           :   IN    std_logic;
          ce_out                          :   OUT   std_logic;
          avg_out                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
          avg_valid                       :   OUT   std_logic;
          mag_out                         :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          mag_valid                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Digital_Spectrometer_from_Chirp_DDC
    USE ENTITY work.Digital_Spectrometer_from_Chirp_DDC(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL rawData_valid                    : std_logic;
  SIGNAL mag_valid_done                   : std_logic;  -- ufix1
  SIGNAL ce_out                           : std_logic;
  SIGNAL mag_valid_done_enb               : std_logic;  -- ufix1
  SIGNAL avg_out_addr                     : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL mag_valid_lastAddr               : std_logic;  -- ufix1
  SIGNAL resetn                           : std_logic;
  SIGNAL check4_done                      : std_logic;  -- ufix1
  SIGNAL mag_out_done                     : std_logic;  -- ufix1
  SIGNAL mag_out_done_enb                 : std_logic;  -- ufix1
  SIGNAL mag_out_lastAddr                 : std_logic;  -- ufix1
  SIGNAL check3_done                      : std_logic;  -- ufix1
  SIGNAL avg_valid_done                   : std_logic;  -- ufix1
  SIGNAL avg_valid_done_enb               : std_logic;  -- ufix1
  SIGNAL avg_valid_lastAddr               : std_logic;  -- ufix1
  SIGNAL check2_done                      : std_logic;  -- ufix1
  SIGNAL avg_out_done                     : std_logic;  -- ufix1
  SIGNAL avg_out_done_enb                 : std_logic;  -- ufix1
  SIGNAL avg_out_active                   : std_logic;  -- ufix1
  SIGNAL holdData_valid                   : std_logic;
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL valid_offset                     : std_logic;
  SIGNAL valid_1                          : std_logic;
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL notDone                          : std_logic;
  SIGNAL avg_out                          : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL avg_valid                        : std_logic;
  SIGNAL mag_out                          : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL mag_valid                        : std_logic;
  SIGNAL avg_out_enb                      : std_logic;  -- ufix1
  SIGNAL avg_out_lastAddr                 : std_logic;  -- ufix1
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL avg_out_signed                   : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_addr_delay_1             : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL avg_out_expected                 : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_ref_hold                 : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_ref                      : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL avg_out_testFailure              : std_logic;  -- ufix1
  SIGNAL avg_valid_addr_delay_1           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL avg_valid_expected               : std_logic;
  SIGNAL avg_valid_ref_hold               : std_logic;
  SIGNAL avg_valid_ref                    : std_logic;
  SIGNAL avg_valid_testFailure            : std_logic;  -- ufix1
  SIGNAL mag_out_signed                   : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL mag_out_addr_delay_1             : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL mag_out_expected                 : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL mag_out_ref_hold                 : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL mag_out_ref                      : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL mag_out_testFailure              : std_logic;  -- ufix1
  SIGNAL mag_valid_addr_delay_1           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL mag_valid_expected               : std_logic;
  SIGNAL mag_valid_ref_hold               : std_logic;
  SIGNAL mag_valid_ref                    : std_logic;
  SIGNAL mag_valid_testFailure            : std_logic;  -- ufix1
  SIGNAL testFailure                      : std_logic;  -- ufix1

BEGIN
  u_Digital_Spectrometer_from_Chirp_DDC : Digital_Spectrometer_from_Chirp_DDC
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              valid => valid_1,
              ce_out => ce_out,
              avg_out => avg_out,  -- sfix32_En4
              avg_valid => avg_valid,
              mag_out => mag_out,  -- sfix26_En15
              mag_valid => mag_valid
              );

  -- Data source for valid
  rawData_valid <= '1';

  mag_valid_done_enb <= mag_valid_done AND ce_out;

  
  mag_valid_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  mag_valid_done <= mag_valid_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_4_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check4_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF mag_valid_done_enb = '1' THEN
        check4_done <= mag_valid_done;
      END IF;
    END IF;
  END PROCESS checkDone_4_process;

  mag_out_done_enb <= mag_out_done AND ce_out;

  
  mag_out_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  mag_out_done <= mag_out_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_3_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check3_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF mag_out_done_enb = '1' THEN
        check3_done <= mag_out_done;
      END IF;
    END IF;
  END PROCESS checkDone_3_process;

  avg_valid_done_enb <= avg_valid_done AND ce_out;

  
  avg_valid_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  avg_valid_done <= avg_valid_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_2_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check2_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF avg_valid_done_enb = '1' THEN
        check2_done <= avg_valid_done;
      END IF;
    END IF;
  END PROCESS checkDone_2_process;

  avg_out_done_enb <= avg_out_done AND ce_out;

  
  avg_out_active <= '1' WHEN avg_out_addr /= to_unsigned(16#3A98#, 14) ELSE
      '0';

  -- holdData reg for Constant_out1
  stimuli_Constant_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_valid <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_valid <= rawData_valid;
    END IF;
  END PROCESS stimuli_Constant_out1_process;

  stimuli_Constant_out1_1: PROCESS (rawData_valid, tb_enb_delay)
  BEGIN
    IF tb_enb_delay = '0' THEN
      valid_offset <= holdData_valid;
    ELSE
      valid_offset <= rawData_valid;
    END IF;
  END PROCESS stimuli_Constant_out1_1;

  valid_1 <= valid_offset AFTER 2 ns;

  snkDonen <=  NOT snkDone;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;


  notDone <= tb_enb_delay AND snkDonen;

  clk_enable <= notDone AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  avg_out_enb <= ce_out AND avg_out_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 15000
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_out_addr <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF avg_out_enb = '1' THEN
        IF avg_out_addr >= to_unsigned(16#3A98#, 14) THEN 
          avg_out_addr <= to_unsigned(16#0000#, 14);
        ELSE 
          avg_out_addr <= avg_out_addr + to_unsigned(16#0001#, 14);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  avg_out_lastAddr <= '1' WHEN avg_out_addr >= to_unsigned(16#3A98#, 14) ELSE
      '0';

  avg_out_done <= avg_out_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF avg_out_done_enb = '1' THEN
        check1_done <= avg_out_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  snkDone <= check4_done AND (check3_done AND (check1_done AND check2_done));

  avg_out_signed <= signed(avg_out);

  avg_out_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for avg_out_expected
  avg_out_expected_fileread: PROCESS (avg_out_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "avg_out_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(31 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    avg_out_expected <= signed(read_data(31 DOWNTO 0));
  END PROCESS avg_out_expected_fileread;

  -- Bypass register to hold avg_out_ref
  DataHold_avg_out_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_out_ref_hold <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        avg_out_ref_hold <= avg_out_expected;
      END IF;
    END IF;
  END PROCESS DataHold_avg_out_ref_process;

  
  avg_out_ref <= avg_out_ref_hold WHEN ce_out = '0' ELSE
      avg_out_expected;

  avg_out_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_out_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND avg_out_signed /= avg_out_ref THEN
        avg_out_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in avg_out_signed: Expected " & to_hex(avg_out_ref) & (" Actual " & to_hex(avg_out_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS avg_out_signed_checker;

  avg_valid_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for avg_valid_expected
  avg_valid_expected_fileread: PROCESS (avg_valid_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "avg_valid_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic;

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      READ(l, read_data);
    END IF;
    avg_valid_expected <= read_data;
  END PROCESS avg_valid_expected_fileread;

  -- Bypass register to hold avg_valid_ref
  DataHold_avg_valid_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_valid_ref_hold <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        avg_valid_ref_hold <= avg_valid_expected;
      END IF;
    END IF;
  END PROCESS DataHold_avg_valid_ref_process;

  
  avg_valid_ref <= avg_valid_ref_hold WHEN ce_out = '0' ELSE
      avg_valid_expected;

  avg_valid_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      avg_valid_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND avg_valid /= avg_valid_ref THEN
        avg_valid_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in avg_valid: Expected " & to_hex(avg_valid_ref) & (" Actual " & to_hex(avg_valid))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS avg_valid_checker;

  mag_out_signed <= signed(mag_out);

  mag_out_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for mag_out_expected
  mag_out_expected_fileread: PROCESS (mag_out_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "mag_out_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(27 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    mag_out_expected <= signed(read_data(25 DOWNTO 0));
  END PROCESS mag_out_expected_fileread;

  -- Bypass register to hold mag_out_ref
  DataHold_mag_out_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mag_out_ref_hold <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        mag_out_ref_hold <= mag_out_expected;
      END IF;
    END IF;
  END PROCESS DataHold_mag_out_ref_process;

  
  mag_out_ref <= mag_out_ref_hold WHEN ce_out = '0' ELSE
      mag_out_expected;

  mag_out_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mag_out_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND mag_out_signed /= mag_out_ref THEN
        mag_out_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in mag_out_signed: Expected " & to_hex(mag_out_ref) & (" Actual " & to_hex(mag_out_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS mag_out_signed_checker;

  mag_valid_addr_delay_1 <= avg_out_addr AFTER 1 ns;

  -- Data source for mag_valid_expected
  mag_valid_expected_fileread: PROCESS (mag_valid_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "mag_valid_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic;

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      READ(l, read_data);
    END IF;
    mag_valid_expected <= read_data;
  END PROCESS mag_valid_expected_fileread;

  -- Bypass register to hold mag_valid_ref
  DataHold_mag_valid_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mag_valid_ref_hold <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        mag_valid_ref_hold <= mag_valid_expected;
      END IF;
    END IF;
  END PROCESS DataHold_mag_valid_ref_process;

  
  mag_valid_ref <= mag_valid_ref_hold WHEN ce_out = '0' ELSE
      mag_valid_expected;

  mag_valid_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mag_valid_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND mag_valid /= mag_valid_ref THEN
        mag_valid_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in mag_valid: Expected " & to_hex(mag_valid_ref) & (" Actual " & to_hex(mag_valid))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS mag_valid_checker;

  testFailure <= mag_valid_testFailure OR (mag_out_testFailure OR (avg_out_testFailure OR avg_valid_testFailure));

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

