-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Digital_Spectrometer.vhd
-- Created: 2025-12-01 13:50:44
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Digital_Spectrometer
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer
-- Hierarchy Level: 1
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Digital_Spectrometer IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        signal_in                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        valid_in                          :   IN    std_logic;
        avg_out                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
        avg_valid                         :   OUT   std_logic;
        mag_out                           :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        mag_valid                         :   OUT   std_logic
        );
END Digital_Spectrometer;


ARCHITECTURE rtl OF Digital_Spectrometer IS

  -- Component Declarations
  COMPONENT alpha512_pt_FFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En15
          dataOut_im                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En15
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Quadrant_Mapper
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block1
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block2
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block3
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block4
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block5
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block6
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block7
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block8
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block9
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block10
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block11
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block12
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block13
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block14
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block15
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block16
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block17
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block18
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block19
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block20
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block21
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag_block22
    PORT( xin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          yin                             :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En15
          );
  END COMPONENT;

  COMPONENT Spectral_Averager
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          signal_in                       :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          valid_in                        :   IN    std_logic;
          avg_out                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : alpha512_pt_FFT
    USE ENTITY work.alpha512_pt_FFT(rtl);

  FOR ALL : Quadrant_Mapper
    USE ENTITY work.Quadrant_Mapper(rtl);

  FOR ALL : CordicKernelMag
    USE ENTITY work.CordicKernelMag(rtl);

  FOR ALL : CordicKernelMag_block
    USE ENTITY work.CordicKernelMag_block(rtl);

  FOR ALL : CordicKernelMag_block1
    USE ENTITY work.CordicKernelMag_block1(rtl);

  FOR ALL : CordicKernelMag_block2
    USE ENTITY work.CordicKernelMag_block2(rtl);

  FOR ALL : CordicKernelMag_block3
    USE ENTITY work.CordicKernelMag_block3(rtl);

  FOR ALL : CordicKernelMag_block4
    USE ENTITY work.CordicKernelMag_block4(rtl);

  FOR ALL : CordicKernelMag_block5
    USE ENTITY work.CordicKernelMag_block5(rtl);

  FOR ALL : CordicKernelMag_block6
    USE ENTITY work.CordicKernelMag_block6(rtl);

  FOR ALL : CordicKernelMag_block7
    USE ENTITY work.CordicKernelMag_block7(rtl);

  FOR ALL : CordicKernelMag_block8
    USE ENTITY work.CordicKernelMag_block8(rtl);

  FOR ALL : CordicKernelMag_block9
    USE ENTITY work.CordicKernelMag_block9(rtl);

  FOR ALL : CordicKernelMag_block10
    USE ENTITY work.CordicKernelMag_block10(rtl);

  FOR ALL : CordicKernelMag_block11
    USE ENTITY work.CordicKernelMag_block11(rtl);

  FOR ALL : CordicKernelMag_block12
    USE ENTITY work.CordicKernelMag_block12(rtl);

  FOR ALL : CordicKernelMag_block13
    USE ENTITY work.CordicKernelMag_block13(rtl);

  FOR ALL : CordicKernelMag_block14
    USE ENTITY work.CordicKernelMag_block14(rtl);

  FOR ALL : CordicKernelMag_block15
    USE ENTITY work.CordicKernelMag_block15(rtl);

  FOR ALL : CordicKernelMag_block16
    USE ENTITY work.CordicKernelMag_block16(rtl);

  FOR ALL : CordicKernelMag_block17
    USE ENTITY work.CordicKernelMag_block17(rtl);

  FOR ALL : CordicKernelMag_block18
    USE ENTITY work.CordicKernelMag_block18(rtl);

  FOR ALL : CordicKernelMag_block19
    USE ENTITY work.CordicKernelMag_block19(rtl);

  FOR ALL : CordicKernelMag_block20
    USE ENTITY work.CordicKernelMag_block20(rtl);

  FOR ALL : CordicKernelMag_block21
    USE ENTITY work.CordicKernelMag_block21(rtl);

  FOR ALL : CordicKernelMag_block22
    USE ENTITY work.CordicKernelMag_block22(rtl);

  FOR ALL : Spectral_Averager
    USE ENTITY work.Spectral_Averager(rtl);

  -- Signals
  SIGNAL alpha512_pt_FFT_out1_re          : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL alpha512_pt_FFT_out1_im          : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL alpha512_pt_FFT_out2             : std_logic;
  SIGNAL Delay_ValidIn_reg                : std_logic_vector(26 DOWNTO 0);  -- ufix1 [27]
  SIGNAL ValidOutDelayed                  : std_logic;
  SIGNAL reset_outval                     : std_logic;
  SIGNAL alpha512_pt_FFT_out1_re_signed   : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL alpha512_pt_FFT_out1_im_signed   : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL qMapReal                         : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL qMapImag                         : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL In1Register                      : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL In2Register                      : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL XQMapped                         : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yQMapped                         : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL XQMapped_signed                  : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yQMapped_signed                  : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin1                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin1                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift1                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout1                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout1                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout1_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout1_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin2                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin2                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift2                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout2                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout2                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout2_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout2_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin3                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin3                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift3                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout3                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout3                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout3_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout3_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin4                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin4                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift4                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout4                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout4                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout4_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout4_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin5                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin5                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift5                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout5                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout5                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout5_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout5_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin6                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin6                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift6                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout6                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout6                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout6_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout6_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin7                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin7                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift7                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout7                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout7                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout7_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout7_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin8                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin8                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift8                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout8                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout8                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout8_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout8_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin9                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin9                             : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift9                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout9                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout9                            : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout9_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout9_signed                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin10                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin10                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift10                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout10                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout10                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout10_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout10_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin11                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin11                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift11                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout11                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout11                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout11_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout11_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin12                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin12                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift12                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout12                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout12                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout12_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout12_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin13                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin13                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift13                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout13                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout13                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout13_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout13_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin14                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin14                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift14                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout14                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout14                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout14_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout14_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin15                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin15                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift15                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout15                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout15                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout15_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout15_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin16                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin16                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift16                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout16                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout16                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout16_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout16_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin17                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin17                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift17                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout17                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout17                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout17_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout17_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin18                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin18                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift18                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout18                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout18                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout18_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout18_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin19                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin19                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift19                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout19                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout19                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout19_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout19_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin20                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin20                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift20                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout20                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout20                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout20_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout20_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin21                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin21                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift21                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout21                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout21                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout21_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout21_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin22                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin22                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift22                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout22                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout22                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout22_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout22_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin23                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin23                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift23                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout23                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL yout23                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout23_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yout23_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin24                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL yin24                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL shift24                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout24                           : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL xout24_signed                    : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin25                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL zeroC                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL outSwitchMag                     : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL xin26                            : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL validOut                         : std_logic;
  SIGNAL Spectral_Averager_avg_out        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Spectral_Averager_valid_out      : std_logic;

BEGIN
  u_512_pt_FFT : alpha512_pt_FFT
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2_0 => enb_1_2_0,
              dataIn => signal_in,  -- sfix16_En15
              validIn => valid_in,
              dataOut_re => alpha512_pt_FFT_out1_re,  -- sfix25_En15
              dataOut_im => alpha512_pt_FFT_out1_im,  -- sfix25_En15
              validOut => alpha512_pt_FFT_out2
              );

  u_QuadrantMapper : Quadrant_Mapper
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2_0 => enb_1_2_0,
              xin => std_logic_vector(In1Register),  -- sfix26_En15
              yin => std_logic_vector(In2Register),  -- sfix26_En15
              xout => XQMapped,  -- sfix26_En15
              yout => yQMapped  -- sfix26_En15
              );

  u_Iteration : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin1),  -- sfix26_En15
              yin => std_logic_vector(yin1),  -- sfix26_En15
              idx => std_logic_vector(shift1),  -- ufix6
              xout => xout1,  -- sfix26_En15
              yout => yout1  -- sfix26_En15
              );

  u_Iteration1 : CordicKernelMag_block
    PORT MAP( xin => std_logic_vector(xin2),  -- sfix26_En15
              yin => std_logic_vector(yin2),  -- sfix26_En15
              idx => std_logic_vector(shift2),  -- ufix6
              xout => xout2,  -- sfix26_En15
              yout => yout2  -- sfix26_En15
              );

  u_Iteration2 : CordicKernelMag_block1
    PORT MAP( xin => std_logic_vector(xin3),  -- sfix26_En15
              yin => std_logic_vector(yin3),  -- sfix26_En15
              idx => std_logic_vector(shift3),  -- ufix6
              xout => xout3,  -- sfix26_En15
              yout => yout3  -- sfix26_En15
              );

  u_Iteration3 : CordicKernelMag_block2
    PORT MAP( xin => std_logic_vector(xin4),  -- sfix26_En15
              yin => std_logic_vector(yin4),  -- sfix26_En15
              idx => std_logic_vector(shift4),  -- ufix6
              xout => xout4,  -- sfix26_En15
              yout => yout4  -- sfix26_En15
              );

  u_Iteration4 : CordicKernelMag_block3
    PORT MAP( xin => std_logic_vector(xin5),  -- sfix26_En15
              yin => std_logic_vector(yin5),  -- sfix26_En15
              idx => std_logic_vector(shift5),  -- ufix6
              xout => xout5,  -- sfix26_En15
              yout => yout5  -- sfix26_En15
              );

  u_Iteration5 : CordicKernelMag_block4
    PORT MAP( xin => std_logic_vector(xin6),  -- sfix26_En15
              yin => std_logic_vector(yin6),  -- sfix26_En15
              idx => std_logic_vector(shift6),  -- ufix6
              xout => xout6,  -- sfix26_En15
              yout => yout6  -- sfix26_En15
              );

  u_Iteration6 : CordicKernelMag_block5
    PORT MAP( xin => std_logic_vector(xin7),  -- sfix26_En15
              yin => std_logic_vector(yin7),  -- sfix26_En15
              idx => std_logic_vector(shift7),  -- ufix6
              xout => xout7,  -- sfix26_En15
              yout => yout7  -- sfix26_En15
              );

  u_Iteration7 : CordicKernelMag_block6
    PORT MAP( xin => std_logic_vector(xin8),  -- sfix26_En15
              yin => std_logic_vector(yin8),  -- sfix26_En15
              idx => std_logic_vector(shift8),  -- ufix6
              xout => xout8,  -- sfix26_En15
              yout => yout8  -- sfix26_En15
              );

  u_Iteration8 : CordicKernelMag_block7
    PORT MAP( xin => std_logic_vector(xin9),  -- sfix26_En15
              yin => std_logic_vector(yin9),  -- sfix26_En15
              idx => std_logic_vector(shift9),  -- ufix6
              xout => xout9,  -- sfix26_En15
              yout => yout9  -- sfix26_En15
              );

  u_Iteration9 : CordicKernelMag_block8
    PORT MAP( xin => std_logic_vector(xin10),  -- sfix26_En15
              yin => std_logic_vector(yin10),  -- sfix26_En15
              idx => std_logic_vector(shift10),  -- ufix6
              xout => xout10,  -- sfix26_En15
              yout => yout10  -- sfix26_En15
              );

  u_Iteration10 : CordicKernelMag_block9
    PORT MAP( xin => std_logic_vector(xin11),  -- sfix26_En15
              yin => std_logic_vector(yin11),  -- sfix26_En15
              idx => std_logic_vector(shift11),  -- ufix6
              xout => xout11,  -- sfix26_En15
              yout => yout11  -- sfix26_En15
              );

  u_Iteration11 : CordicKernelMag_block10
    PORT MAP( xin => std_logic_vector(xin12),  -- sfix26_En15
              yin => std_logic_vector(yin12),  -- sfix26_En15
              idx => std_logic_vector(shift12),  -- ufix6
              xout => xout12,  -- sfix26_En15
              yout => yout12  -- sfix26_En15
              );

  u_Iteration12 : CordicKernelMag_block11
    PORT MAP( xin => std_logic_vector(xin13),  -- sfix26_En15
              yin => std_logic_vector(yin13),  -- sfix26_En15
              idx => std_logic_vector(shift13),  -- ufix6
              xout => xout13,  -- sfix26_En15
              yout => yout13  -- sfix26_En15
              );

  u_Iteration13 : CordicKernelMag_block12
    PORT MAP( xin => std_logic_vector(xin14),  -- sfix26_En15
              yin => std_logic_vector(yin14),  -- sfix26_En15
              idx => std_logic_vector(shift14),  -- ufix6
              xout => xout14,  -- sfix26_En15
              yout => yout14  -- sfix26_En15
              );

  u_Iteration14 : CordicKernelMag_block13
    PORT MAP( xin => std_logic_vector(xin15),  -- sfix26_En15
              yin => std_logic_vector(yin15),  -- sfix26_En15
              idx => std_logic_vector(shift15),  -- ufix6
              xout => xout15,  -- sfix26_En15
              yout => yout15  -- sfix26_En15
              );

  u_Iteration15 : CordicKernelMag_block14
    PORT MAP( xin => std_logic_vector(xin16),  -- sfix26_En15
              yin => std_logic_vector(yin16),  -- sfix26_En15
              idx => std_logic_vector(shift16),  -- ufix6
              xout => xout16,  -- sfix26_En15
              yout => yout16  -- sfix26_En15
              );

  u_Iteration16 : CordicKernelMag_block15
    PORT MAP( xin => std_logic_vector(xin17),  -- sfix26_En15
              yin => std_logic_vector(yin17),  -- sfix26_En15
              idx => std_logic_vector(shift17),  -- ufix6
              xout => xout17,  -- sfix26_En15
              yout => yout17  -- sfix26_En15
              );

  u_Iteration17 : CordicKernelMag_block16
    PORT MAP( xin => std_logic_vector(xin18),  -- sfix26_En15
              yin => std_logic_vector(yin18),  -- sfix26_En15
              idx => std_logic_vector(shift18),  -- ufix6
              xout => xout18,  -- sfix26_En15
              yout => yout18  -- sfix26_En15
              );

  u_Iteration18 : CordicKernelMag_block17
    PORT MAP( xin => std_logic_vector(xin19),  -- sfix26_En15
              yin => std_logic_vector(yin19),  -- sfix26_En15
              idx => std_logic_vector(shift19),  -- ufix6
              xout => xout19,  -- sfix26_En15
              yout => yout19  -- sfix26_En15
              );

  u_Iteration19 : CordicKernelMag_block18
    PORT MAP( xin => std_logic_vector(xin20),  -- sfix26_En15
              yin => std_logic_vector(yin20),  -- sfix26_En15
              idx => std_logic_vector(shift20),  -- ufix6
              xout => xout20,  -- sfix26_En15
              yout => yout20  -- sfix26_En15
              );

  u_Iteration20 : CordicKernelMag_block19
    PORT MAP( xin => std_logic_vector(xin21),  -- sfix26_En15
              yin => std_logic_vector(yin21),  -- sfix26_En15
              idx => std_logic_vector(shift21),  -- ufix6
              xout => xout21,  -- sfix26_En15
              yout => yout21  -- sfix26_En15
              );

  u_Iteration21 : CordicKernelMag_block20
    PORT MAP( xin => std_logic_vector(xin22),  -- sfix26_En15
              yin => std_logic_vector(yin22),  -- sfix26_En15
              idx => std_logic_vector(shift22),  -- ufix6
              xout => xout22,  -- sfix26_En15
              yout => yout22  -- sfix26_En15
              );

  u_Iteration22 : CordicKernelMag_block21
    PORT MAP( xin => std_logic_vector(xin23),  -- sfix26_En15
              yin => std_logic_vector(yin23),  -- sfix26_En15
              idx => std_logic_vector(shift23),  -- ufix6
              xout => xout23,  -- sfix26_En15
              yout => yout23  -- sfix26_En15
              );

  u_Iteration23 : CordicKernelMag_block22
    PORT MAP( xin => std_logic_vector(xin24),  -- sfix26_En15
              yin => std_logic_vector(yin24),  -- sfix26_En15
              idx => std_logic_vector(shift24),  -- ufix6
              xout => xout24  -- sfix26_En15
              );

  u_Spectral_Averager : Spectral_Averager
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2_0 => enb_1_2_0,
              signal_in => std_logic_vector(xin26),  -- sfix26_En15
              valid_in => validOut,
              avg_out => Spectral_Averager_avg_out,  -- sfix32_En4
              valid_out => Spectral_Averager_valid_out
              );

  Delay_ValidIn_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_ValidIn_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        Delay_ValidIn_reg(0) <= alpha512_pt_FFT_out2;
        Delay_ValidIn_reg(26 DOWNTO 1) <= Delay_ValidIn_reg(25 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay_ValidIn_process;

  ValidOutDelayed <= Delay_ValidIn_reg(26);

  reset_outval <=  NOT ValidOutDelayed;

  -- Complex to Magnitude-Angle
  alpha512_pt_FFT_out1_re_signed <= signed(alpha512_pt_FFT_out1_re);

  qMapReal <= resize(alpha512_pt_FFT_out1_re_signed, 26);

  alpha512_pt_FFT_out1_im_signed <= signed(alpha512_pt_FFT_out1_im);

  qMapImag <= resize(alpha512_pt_FFT_out1_im_signed, 26);

  DelayRealInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In1Register <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        In1Register <= qMapReal;
      END IF;
    END IF;
  END PROCESS DelayRealInput_process;


  DelayImagInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In2Register <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        In2Register <= qMapImag;
      END IF;
    END IF;
  END PROCESS DelayImagInput_process;


  XQMapped_signed <= signed(XQMapped);

  yQMapped_signed <= signed(yQMapped);

  DelayQuadMapper1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin1 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin1 <= XQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper1_process;


  DelayQuadMapper2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin1 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin1 <= yQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper2_process;


  shift1 <= to_unsigned(16#01#, 6);

  xout1_signed <= signed(xout1);

  yout1_signed <= signed(yout1);

  Pipeline1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin2 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin2 <= xout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_process;


  Pipeline11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin2 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin2 <= yout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_process;


  shift2 <= to_unsigned(16#02#, 6);

  xout2_signed <= signed(xout2);

  yout2_signed <= signed(yout2);

  Pipeline2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin3 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin3 <= xout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_process;


  Pipeline21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin3 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin3 <= yout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline21_process;


  shift3 <= to_unsigned(16#03#, 6);

  xout3_signed <= signed(xout3);

  yout3_signed <= signed(yout3);

  Pipeline3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin4 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin4 <= xout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_process;


  Pipeline31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin4 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin4 <= yout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline31_process;


  shift4 <= to_unsigned(16#04#, 6);

  xout4_signed <= signed(xout4);

  yout4_signed <= signed(yout4);

  Pipeline4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin5 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin5 <= xout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_process;


  Pipeline41_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin5 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin5 <= yout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline41_process;


  shift5 <= to_unsigned(16#05#, 6);

  xout5_signed <= signed(xout5);

  yout5_signed <= signed(yout5);

  Pipeline5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin6 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin6 <= xout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_process;


  Pipeline51_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin6 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin6 <= yout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline51_process;


  shift6 <= to_unsigned(16#06#, 6);

  xout6_signed <= signed(xout6);

  yout6_signed <= signed(yout6);

  Pipeline6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin7 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin7 <= xout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_process;


  Pipeline61_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin7 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin7 <= yout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline61_process;


  shift7 <= to_unsigned(16#07#, 6);

  xout7_signed <= signed(xout7);

  yout7_signed <= signed(yout7);

  Pipeline7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin8 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin8 <= xout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_process;


  Pipeline71_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin8 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin8 <= yout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline71_process;


  shift8 <= to_unsigned(16#08#, 6);

  xout8_signed <= signed(xout8);

  yout8_signed <= signed(yout8);

  Pipeline8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin9 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin9 <= xout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_process;


  Pipeline81_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin9 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin9 <= yout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline81_process;


  shift9 <= to_unsigned(16#09#, 6);

  xout9_signed <= signed(xout9);

  yout9_signed <= signed(yout9);

  Pipeline9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin10 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin10 <= xout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_process;


  Pipeline91_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin10 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin10 <= yout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline91_process;


  shift10 <= to_unsigned(16#0A#, 6);

  xout10_signed <= signed(xout10);

  yout10_signed <= signed(yout10);

  Pipeline10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin11 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin11 <= xout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_process;


  Pipeline101_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin11 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin11 <= yout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline101_process;


  shift11 <= to_unsigned(16#0B#, 6);

  xout11_signed <= signed(xout11);

  yout11_signed <= signed(yout11);

  Pipeline111_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin12 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin12 <= xout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline111_process;


  Pipeline112_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin12 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin12 <= yout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline112_process;


  shift12 <= to_unsigned(16#0C#, 6);

  xout12_signed <= signed(xout12);

  yout12_signed <= signed(yout12);

  Pipeline12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin13 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin13 <= xout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_process;


  Pipeline121_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin13 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin13 <= yout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline121_process;


  shift13 <= to_unsigned(16#0D#, 6);

  xout13_signed <= signed(xout13);

  yout13_signed <= signed(yout13);

  Pipeline13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin14 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin14 <= xout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_process;


  Pipeline131_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin14 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin14 <= yout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline131_process;


  shift14 <= to_unsigned(16#0E#, 6);

  xout14_signed <= signed(xout14);

  yout14_signed <= signed(yout14);

  Pipeline14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin15 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin15 <= xout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_process;


  Pipeline141_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin15 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin15 <= yout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline141_process;


  shift15 <= to_unsigned(16#0F#, 6);

  xout15_signed <= signed(xout15);

  yout15_signed <= signed(yout15);

  Pipeline15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin16 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin16 <= xout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline15_process;


  Pipeline151_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin16 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin16 <= yout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline151_process;


  shift16 <= to_unsigned(16#10#, 6);

  xout16_signed <= signed(xout16);

  yout16_signed <= signed(yout16);

  Pipeline16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin17 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin17 <= xout16_signed;
      END IF;
    END IF;
  END PROCESS Pipeline16_process;


  Pipeline161_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin17 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin17 <= yout16_signed;
      END IF;
    END IF;
  END PROCESS Pipeline161_process;


  shift17 <= to_unsigned(16#11#, 6);

  xout17_signed <= signed(xout17);

  yout17_signed <= signed(yout17);

  Pipeline17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin18 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin18 <= xout17_signed;
      END IF;
    END IF;
  END PROCESS Pipeline17_process;


  Pipeline171_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin18 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin18 <= yout17_signed;
      END IF;
    END IF;
  END PROCESS Pipeline171_process;


  shift18 <= to_unsigned(16#12#, 6);

  xout18_signed <= signed(xout18);

  yout18_signed <= signed(yout18);

  Pipeline18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin19 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin19 <= xout18_signed;
      END IF;
    END IF;
  END PROCESS Pipeline18_process;


  Pipeline181_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin19 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin19 <= yout18_signed;
      END IF;
    END IF;
  END PROCESS Pipeline181_process;


  shift19 <= to_unsigned(16#13#, 6);

  xout19_signed <= signed(xout19);

  yout19_signed <= signed(yout19);

  Pipeline19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin20 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin20 <= xout19_signed;
      END IF;
    END IF;
  END PROCESS Pipeline19_process;


  Pipeline191_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin20 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin20 <= yout19_signed;
      END IF;
    END IF;
  END PROCESS Pipeline191_process;


  shift20 <= to_unsigned(16#14#, 6);

  xout20_signed <= signed(xout20);

  yout20_signed <= signed(yout20);

  Pipeline20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin21 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin21 <= xout20_signed;
      END IF;
    END IF;
  END PROCESS Pipeline20_process;


  Pipeline201_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin21 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin21 <= yout20_signed;
      END IF;
    END IF;
  END PROCESS Pipeline201_process;


  shift21 <= to_unsigned(16#15#, 6);

  xout21_signed <= signed(xout21);

  yout21_signed <= signed(yout21);

  Pipeline211_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin22 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin22 <= xout21_signed;
      END IF;
    END IF;
  END PROCESS Pipeline211_process;


  Pipeline212_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin22 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin22 <= yout21_signed;
      END IF;
    END IF;
  END PROCESS Pipeline212_process;


  shift22 <= to_unsigned(16#16#, 6);

  xout22_signed <= signed(xout22);

  yout22_signed <= signed(yout22);

  Pipeline22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin23 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin23 <= xout22_signed;
      END IF;
    END IF;
  END PROCESS Pipeline22_process;


  Pipeline221_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin23 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin23 <= yout22_signed;
      END IF;
    END IF;
  END PROCESS Pipeline221_process;


  shift23 <= to_unsigned(16#17#, 6);

  xout23_signed <= signed(xout23);

  yout23_signed <= signed(yout23);

  Pipeline23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin24 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin24 <= xout23_signed;
      END IF;
    END IF;
  END PROCESS Pipeline23_process;


  Pipeline231_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin24 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        yin24 <= yout23_signed;
      END IF;
    END IF;
  END PROCESS Pipeline231_process;


  shift24 <= to_unsigned(16#18#, 6);

  xout24_signed <= signed(xout24);

  Pipeline24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin25 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin25 <= xout24_signed;
      END IF;
    END IF;
  END PROCESS Pipeline24_process;


  zeroC <= to_signed(16#0000000#, 26);

  
  outSwitchMag <= xin25 WHEN reset_outval = '0' ELSE
      zeroC;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin26 <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        xin26 <= outSwitchMag;
      END IF;
    END IF;
  END PROCESS Output_Register_process;


  DelayValidOut_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        validOut <= ValidOutDelayed;
      END IF;
    END IF;
  END PROCESS DelayValidOut_process;


  mag_out <= std_logic_vector(xin26);

  avg_out <= Spectral_Averager_avg_out;

  avg_valid <= Spectral_Averager_valid_out;

  mag_valid <= validOut;

END rtl;

