-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\spec_avg_CRD.vhd
-- Created: 2025-12-01 13:47:26
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.66667e-08
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: spec_avg_CRD
-- Source Path: spec_avg_CRD
-- Hierarchy Level: 0
-- Model version: 7.327
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY spec_avg_CRD IS
END spec_avg_CRD;


ARCHITECTURE rtl OF spec_avg_CRD IS

BEGIN
  -- Digital Spectrometer from Chirp DDC

END rtl;

