-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\Spec_Avg.vhd
-- Created: 2025-12-01 12:25:10
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Spec_Avg
-- Source Path: spec_avg_CRD/ddc_spec_avg/Spec Avg
-- Hierarchy Level: 1
-- Model version: 7.280
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ddc_spec_avg_pkg.ALL;

ENTITY Spec_Avg IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        sample_in                         :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        valid_in                          :   IN    std_logic;
        avg_out                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
        valid_out                         :   OUT   std_logic
        );
END Spec_Avg;


ARCHITECTURE rtl OF Spec_Avg IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL stateControl                     : std_logic;
  SIGNAL stateControl_1                   : std_logic;
  SIGNAL enb_1_2_0_gated                  : std_logic;
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL count_step                       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL modValue                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_reset                      : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL stateControl_3                   : std_logic;
  SIGNAL stateControl_4                   : std_logic;
  SIGNAL enb_1_2_0_gated_1                : std_logic;
  SIGNAL Fast_Counter_out1                : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_from                       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_1                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL zero                             : std_logic;
  SIGNAL Fast_Counter_out2                : std_logic;
  SIGNAL count_step_1                     : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL modValue_1                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count_reset_1                    : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL stateControl_5                   : std_logic;
  SIGNAL stateControl_6                   : std_logic;
  SIGNAL enb_1_2_0_gated_2                : std_logic;
  SIGNAL Spectral_Averaging_out1          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count_from_1                     : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count_2                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL need_to_wrap_1                   : std_logic;
  SIGNAL count_value_1                    : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count_3                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count_4                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Bit_Concat_out1                  : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Constant_out1_1                  : std_logic;
  SIGNAL Delay_reg                        : vector_of_unsigned14(0 TO 13311);  -- ufix14 [13312]
  SIGNAL Delay_out1                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL sample_in_signed                 : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL Simple_Dual_Port_RAM_out1        : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL Simple_Dual_Port_RAM_out1_signed : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL Add_sub_cast                     : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL Add_sub_cast_1                   : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL Add_sub_temp                     : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- sfix16_En7
  SIGNAL Add1_out1                        : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL Delay1_reg                       : vector_of_signed32(0 TO 511);  -- sfix32 [512]
  SIGNAL Delay1_out1                      : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL Add1_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL zero_2                           : std_logic;
  SIGNAL Spectral_Averaging_out2          : std_logic;
  SIGNAL stateControl_7                   : std_logic;
  SIGNAL stateControl_8                   : std_logic;
  SIGNAL enb_1_2_0_gated_3                : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL OR_out1                          : std_logic;

BEGIN
  u_Simple_Dual_Port_RAM : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 14,
                 DataWidth => 26
                 )
    PORT MAP( clk => clk,
              enb_1_2_0 => enb_1_2_0,
              wr_din => sample_in,
              wr_addr => std_logic_vector(Bit_Concat_out1),
              wr_en => Constant_out1_1,
              rd_addr => std_logic_vector(Delay_out1),
              dout => Simple_Dual_Port_RAM_out1
              );

  stateControl <= '1';

  delayMatch3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      stateControl_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        stateControl_1 <= stateControl;
      END IF;
    END IF;
  END PROCESS delayMatch3_process;


  enb_1_2_0_gated <= stateControl_1 AND enb_1_2_0;

  NOT_out1 <=  NOT valid_in;

  -- Modulo, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 511
  count_step <= to_unsigned(16#001#, 9);

  modValue <= to_unsigned(16#1FF#, 9);

  count_reset <= to_unsigned(16#000#, 9);

  stateControl_3 <= '1';

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      stateControl_4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        stateControl_4 <= stateControl_3;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  enb_1_2_0_gated_1 <= stateControl_4 AND enb_1_2_0;

  count_from <= Fast_Counter_out1 - modValue;

  count <= Fast_Counter_out1 + count_step;

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  
  count_1 <= count_value WHEN NOT_out1 = '0' ELSE
      count_reset;

  Fast_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Fast_Counter_out1 <= to_unsigned(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0_gated_1 = '1' THEN
        Fast_Counter_out1 <= count_1;
      END IF;
    END IF;
  END PROCESS Fast_Counter_process;


  
  need_to_wrap <= '1' WHEN Fast_Counter_out1 > to_unsigned(16#1FE#, 9) ELSE
      '0';

  zero <= '0';

  
  Fast_Counter_out2 <= need_to_wrap WHEN NOT_out1 = '0' ELSE
      zero;

  -- Modulo, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 26
  count_step_1 <= to_unsigned(16#01#, 5);

  modValue_1 <= to_unsigned(16#1A#, 5);

  count_reset_1 <= to_unsigned(16#00#, 5);

  stateControl_5 <= '1';

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      stateControl_6 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        stateControl_6 <= stateControl_5;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  enb_1_2_0_gated_2 <= stateControl_6 AND enb_1_2_0;

  count_from_1 <= Spectral_Averaging_out1 - modValue_1;

  count_2 <= Spectral_Averaging_out1 + count_step_1;

  
  need_to_wrap_1 <= '1' WHEN Spectral_Averaging_out1 > to_unsigned(16#19#, 5) ELSE
      '0';

  
  count_value_1 <= count_2 WHEN need_to_wrap_1 = '0' ELSE
      count_from_1;

  
  count_3 <= Spectral_Averaging_out1 WHEN Fast_Counter_out2 = '0' ELSE
      count_value_1;

  
  count_4 <= count_3 WHEN NOT_out1 = '0' ELSE
      count_reset_1;

  Spectral_Averaging_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Spectral_Averaging_out1 <= to_unsigned(16#00#, 5);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0_gated_2 = '1' THEN
        Spectral_Averaging_out1 <= count_4;
      END IF;
    END IF;
  END PROCESS Spectral_Averaging_process;


  Bit_Concat_out1 <= Spectral_Averaging_out1 & Fast_Counter_out1;

  Constant_out1 <= '1';

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Constant_out1_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        Constant_out1_1 <= Constant_out1;
      END IF;
    END IF;
  END PROCESS delayMatch2_process;


  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_reg <= (OTHERS => to_unsigned(16#0000#, 14));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        Delay_reg(0) <= Bit_Concat_out1;
        Delay_reg(1 TO 13311) <= Delay_reg(0 TO 13310);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(13311);

  sample_in_signed <= signed(sample_in);

  Simple_Dual_Port_RAM_out1_signed <= signed(Simple_Dual_Port_RAM_out1);

  Add_sub_cast <= resize(sample_in_signed, 27);
  Add_sub_cast_1 <= resize(Simple_Dual_Port_RAM_out1_signed, 27);
  Add_sub_temp <= Add_sub_cast - Add_sub_cast_1;
  Add_out1 <= Add_sub_temp(23 DOWNTO 8);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_reg <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0_gated = '1' THEN
        Delay1_reg(0) <= Add1_out1;
        Delay1_reg(1 TO 511) <= Delay1_reg(0 TO 510);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(511);

  Add1_add_cast <= resize(Add_out1(15 DOWNTO 3), 32);
  Add1_out1 <= Delay1_out1 + Add1_add_cast;

  avg_out <= std_logic_vector(Add1_out1);

  zero_2 <= '0';

  
  Spectral_Averaging_out2 <= need_to_wrap_1 WHEN NOT_out1 = '0' ELSE
      zero_2;

  stateControl_7 <= '1';

  delayMatch4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      stateControl_8 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        stateControl_8 <= stateControl_7;
      END IF;
    END IF;
  END PROCESS delayMatch4_process;


  enb_1_2_0_gated_3 <= stateControl_8 AND enb_1_2_0;

  OR_out1 <= Delay2_out1 OR Spectral_Averaging_out2;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0_gated_3 = '1' THEN
        Delay2_out1 <= OR_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  valid_out <= Delay2_out1;

END rtl;

