-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spec_avg_CRD\WaveformGen_block.vhd
-- Created: 2025-12-01 13:50:43
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: WaveformGen_block
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/DDC/LO/WaveformGen
-- Hierarchy Level: 3
-- Model version: 7.329
-- 
-- Wave form Generation Component
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY WaveformGen_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        phaseIdx                          :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13_E18
        cosine                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END WaveformGen_block;


ARCHITECTURE rtl OF WaveformGen_block IS

  -- Component Declarations
  COMPONENT LookUpTableGen_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          lutaddr                         :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
          lutoutput                       :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : LookUpTableGen_block
    USE ENTITY work.LookUpTableGen_block(rtl);

  -- Signals
  SIGNAL phaseIdx_unsigned                : unsigned(12 DOWNTO 0);  -- ufix13_E18
  SIGNAL phaseIdxReg                      : unsigned(12 DOWNTO 0);  -- ufix13_E18
  SIGNAL selsign                          : std_logic;  -- ufix1
  SIGNAL seladdr                          : std_logic;  -- ufix1
  SIGNAL selsign_cos                      : std_logic;  -- ufix1
  SIGNAL SelsignCosRegister_reg           : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL selsign_cosreg                   : std_logic;  -- ufix1
  SIGNAL lutaddrexd                       : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL addreqzero                       : std_logic;  -- ufix1
  SIGNAL validcnt                         : std_logic;  -- ufix1
  SIGNAL validEnb                         : std_logic;  -- ufix1
  SIGNAL enbreg                           : std_logic;  -- ufix1
  SIGNAL addrOverFcos                     : std_logic;  -- ufix1
  SIGNAL lutaddrmax                       : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL lutaddr1                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL lutaddr2                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL lutaddrcos                       : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL AddrOverFcosRegister_reg         : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL addrOverFcosreg                  : std_logic;  -- ufix1
  SIGNAL lutoutcos                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL lutoutcos_signed                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL ampOne                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL lutoutcos_ampOne                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL uminus_cast                      : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL uminus_cast_1                    : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL lutoutcos_ampOne_inv             : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL cosine_tmp                       : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_CosineWave_inst : LookUpTableGen_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              lutaddr => std_logic_vector(lutaddrcos),  -- ufix11
              lutoutput => lutoutcos  -- sfix16_En14
              );

  phaseIdx_unsigned <= unsigned(phaseIdx);

  phaseIdxRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phaseIdxReg <= to_unsigned(16#0000#, 13);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        phaseIdxReg <= phaseIdx_unsigned;
      END IF;
    END IF;
  END PROCESS phaseIdxRegister_process;


  -- Sine sign selection signal
  selsign <= phaseIdxReg(12);

  seladdr <= phaseIdxReg(11);

  -- Cosine sign selection signal
  selsign_cos <= selsign XOR seladdr;

  SelsignCosRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      SelsignCosRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        SelsignCosRegister_reg(0) <= selsign_cos;
        SelsignCosRegister_reg(2 DOWNTO 1) <= SelsignCosRegister_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS SelsignCosRegister_process;

  selsign_cosreg <= SelsignCosRegister_reg(2);

  -- Get extended LUT address for overflow handling
  lutaddrexd <= phaseIdxReg(11 DOWNTO 0);

  -- Detect cosine overflow
  
  addreqzero <= '1' WHEN lutaddrexd = to_unsigned(16#000#, 12) ELSE
      '0';

  
  validEnb <= '1' WHEN validcnt < '1' ELSE
      '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 1
  counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validcnt <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND validEnb = '1' THEN
        validcnt <=  NOT validcnt;
      END IF;
    END IF;
  END PROCESS counter_process;


  
  enbreg <= '1' WHEN validcnt = '1' ELSE
      '0';

  addrOverFcos <= addreqzero AND enbreg;

  -- Map LUT address in correct phase
  lutaddrmax <= to_unsigned(16#800#, 12);

  lutaddr1 <= phaseIdxReg(10 DOWNTO 0);

  lutaddr2 <= resize(resize(lutaddrmax, 13) - resize(lutaddr1, 13), 11);

  
  lutaddrcos <= lutaddr2 WHEN seladdr = '0' ELSE
      lutaddr1;

  AddrOverFcosRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      AddrOverFcosRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        AddrOverFcosRegister_reg(0) <= addrOverFcos;
        AddrOverFcosRegister_reg(2 DOWNTO 1) <= AddrOverFcosRegister_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS AddrOverFcosRegister_process;

  addrOverFcosreg <= AddrOverFcosRegister_reg(2);

  lutoutcos_signed <= signed(lutoutcos);

  ampOne <= to_signed(16#4000#, 16);

  -- Assign cosine amplitude One
  
  lutoutcos_ampOne <= lutoutcos_signed WHEN addrOverFcosreg = '0' ELSE
      ampOne;

  uminus_cast <= resize(lutoutcos_ampOne, 17);
  uminus_cast_1 <=  - (uminus_cast);
  lutoutcos_ampOne_inv <= uminus_cast_1(15 DOWNTO 0);

  -- Select sign of cosine output
  
  cosine_tmp <= lutoutcos_ampOne WHEN selsign_cosreg = '0' ELSE
      lutoutcos_ampOne_inv;

  cosine <= std_logic_vector(cosine_tmp);

END rtl;

