-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ddc_simulink_CRD_fixed\Chirp.vhd
-- Created: 2025-11-17 12:04:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Chirp
-- Source Path: ddc_simulink_CRD_fixed/Chirp
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ddc_simulink_CRD_fixed_pkg.ALL;

ENTITY Chirp IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid                             :   IN    std_logic;
        X                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END Chirp;


ARCHITECTURE rtl OF Chirp IS

  -- Component Declarations
  COMPONENT Counter_Limited
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          y                               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT NCO1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          inc                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          validIn                         :   IN    std_logic;
          cosine                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Counter_Limited
    USE ENTITY work.Counter_Limited(rtl);

  FOR ALL : NCO1
    USE ENTITY work.NCO1(rtl);

  -- Constants
  CONSTANT alpha1_D_Lookup_Table1_data    : vector_of_unsigned32(0 TO 1200) := 
    (to_unsigned(10000000, 32), to_unsigned(10008333, 32), to_unsigned(10016667, 32), to_unsigned(10025000, 32),
     to_unsigned(10033333, 32), to_unsigned(10041667, 32), to_unsigned(10050000, 32), to_unsigned(10058333, 32),
     to_unsigned(10066667, 32), to_unsigned(10075000, 32), to_unsigned(10083333, 32), to_unsigned(10091667, 32),
     to_unsigned(10100000, 32), to_unsigned(10108333, 32), to_unsigned(10116667, 32), to_unsigned(10125000, 32),
     to_unsigned(10133333, 32), to_unsigned(10141667, 32), to_unsigned(10150000, 32), to_unsigned(10158333, 32),
     to_unsigned(10166667, 32), to_unsigned(10175000, 32), to_unsigned(10183333, 32), to_unsigned(10191667, 32),
     to_unsigned(10200000, 32), to_unsigned(10208333, 32), to_unsigned(10216667, 32), to_unsigned(10225000, 32),
     to_unsigned(10233333, 32), to_unsigned(10241667, 32), to_unsigned(10250000, 32), to_unsigned(10258333, 32),
     to_unsigned(10266667, 32), to_unsigned(10275000, 32), to_unsigned(10283333, 32), to_unsigned(10291667, 32),
     to_unsigned(10300000, 32), to_unsigned(10308333, 32), to_unsigned(10316667, 32), to_unsigned(10325000, 32),
     to_unsigned(10333333, 32), to_unsigned(10341667, 32), to_unsigned(10350000, 32), to_unsigned(10358333, 32),
     to_unsigned(10366667, 32), to_unsigned(10375000, 32), to_unsigned(10383333, 32), to_unsigned(10391667, 32),
     to_unsigned(10400000, 32), to_unsigned(10408333, 32), to_unsigned(10416667, 32), to_unsigned(10425000, 32),
     to_unsigned(10433333, 32), to_unsigned(10441667, 32), to_unsigned(10450000, 32), to_unsigned(10458333, 32),
     to_unsigned(10466667, 32), to_unsigned(10475000, 32), to_unsigned(10483333, 32), to_unsigned(10491667, 32),
     to_unsigned(10500000, 32), to_unsigned(10508333, 32), to_unsigned(10516667, 32), to_unsigned(10525000, 32),
     to_unsigned(10533333, 32), to_unsigned(10541667, 32), to_unsigned(10550000, 32), to_unsigned(10558333, 32),
     to_unsigned(10566667, 32), to_unsigned(10575000, 32), to_unsigned(10583333, 32), to_unsigned(10591667, 32),
     to_unsigned(10600000, 32), to_unsigned(10608333, 32), to_unsigned(10616667, 32), to_unsigned(10625000, 32),
     to_unsigned(10633333, 32), to_unsigned(10641667, 32), to_unsigned(10650000, 32), to_unsigned(10658333, 32),
     to_unsigned(10666667, 32), to_unsigned(10675000, 32), to_unsigned(10683333, 32), to_unsigned(10691667, 32),
     to_unsigned(10700000, 32), to_unsigned(10708333, 32), to_unsigned(10716667, 32), to_unsigned(10725000, 32),
     to_unsigned(10733333, 32), to_unsigned(10741667, 32), to_unsigned(10750000, 32), to_unsigned(10758333, 32),
     to_unsigned(10766667, 32), to_unsigned(10775000, 32), to_unsigned(10783333, 32), to_unsigned(10791667, 32),
     to_unsigned(10800000, 32), to_unsigned(10808333, 32), to_unsigned(10816667, 32), to_unsigned(10825000, 32),
     to_unsigned(10833333, 32), to_unsigned(10841667, 32), to_unsigned(10850000, 32), to_unsigned(10858333, 32),
     to_unsigned(10866667, 32), to_unsigned(10875000, 32), to_unsigned(10883333, 32), to_unsigned(10891667, 32),
     to_unsigned(10900000, 32), to_unsigned(10908333, 32), to_unsigned(10916667, 32), to_unsigned(10925000, 32),
     to_unsigned(10933333, 32), to_unsigned(10941667, 32), to_unsigned(10950000, 32), to_unsigned(10958333, 32),
     to_unsigned(10966667, 32), to_unsigned(10975000, 32), to_unsigned(10983333, 32), to_unsigned(10991667, 32),
     to_unsigned(11000000, 32), to_unsigned(11008333, 32), to_unsigned(11016667, 32), to_unsigned(11025000, 32),
     to_unsigned(11033333, 32), to_unsigned(11041667, 32), to_unsigned(11050000, 32), to_unsigned(11058333, 32),
     to_unsigned(11066667, 32), to_unsigned(11075000, 32), to_unsigned(11083333, 32), to_unsigned(11091667, 32),
     to_unsigned(11100000, 32), to_unsigned(11108333, 32), to_unsigned(11116667, 32), to_unsigned(11125000, 32),
     to_unsigned(11133333, 32), to_unsigned(11141667, 32), to_unsigned(11150000, 32), to_unsigned(11158333, 32),
     to_unsigned(11166667, 32), to_unsigned(11175000, 32), to_unsigned(11183333, 32), to_unsigned(11191667, 32),
     to_unsigned(11200000, 32), to_unsigned(11208333, 32), to_unsigned(11216667, 32), to_unsigned(11225000, 32),
     to_unsigned(11233333, 32), to_unsigned(11241667, 32), to_unsigned(11250000, 32), to_unsigned(11258333, 32),
     to_unsigned(11266667, 32), to_unsigned(11275000, 32), to_unsigned(11283333, 32), to_unsigned(11291667, 32),
     to_unsigned(11300000, 32), to_unsigned(11308333, 32), to_unsigned(11316667, 32), to_unsigned(11325000, 32),
     to_unsigned(11333333, 32), to_unsigned(11341667, 32), to_unsigned(11350000, 32), to_unsigned(11358333, 32),
     to_unsigned(11366667, 32), to_unsigned(11375000, 32), to_unsigned(11383333, 32), to_unsigned(11391667, 32),
     to_unsigned(11400000, 32), to_unsigned(11408333, 32), to_unsigned(11416667, 32), to_unsigned(11425000, 32),
     to_unsigned(11433333, 32), to_unsigned(11441667, 32), to_unsigned(11450000, 32), to_unsigned(11458333, 32),
     to_unsigned(11466667, 32), to_unsigned(11475000, 32), to_unsigned(11483333, 32), to_unsigned(11491667, 32),
     to_unsigned(11500000, 32), to_unsigned(11508333, 32), to_unsigned(11516667, 32), to_unsigned(11525000, 32),
     to_unsigned(11533333, 32), to_unsigned(11541667, 32), to_unsigned(11550000, 32), to_unsigned(11558333, 32),
     to_unsigned(11566667, 32), to_unsigned(11575000, 32), to_unsigned(11583333, 32), to_unsigned(11591667, 32),
     to_unsigned(11600000, 32), to_unsigned(11608333, 32), to_unsigned(11616667, 32), to_unsigned(11625000, 32),
     to_unsigned(11633333, 32), to_unsigned(11641667, 32), to_unsigned(11650000, 32), to_unsigned(11658333, 32),
     to_unsigned(11666667, 32), to_unsigned(11675000, 32), to_unsigned(11683333, 32), to_unsigned(11691667, 32),
     to_unsigned(11700000, 32), to_unsigned(11708333, 32), to_unsigned(11716667, 32), to_unsigned(11725000, 32),
     to_unsigned(11733333, 32), to_unsigned(11741667, 32), to_unsigned(11750000, 32), to_unsigned(11758333, 32),
     to_unsigned(11766667, 32), to_unsigned(11775000, 32), to_unsigned(11783333, 32), to_unsigned(11791667, 32),
     to_unsigned(11800000, 32), to_unsigned(11808333, 32), to_unsigned(11816667, 32), to_unsigned(11825000, 32),
     to_unsigned(11833333, 32), to_unsigned(11841667, 32), to_unsigned(11850000, 32), to_unsigned(11858333, 32),
     to_unsigned(11866667, 32), to_unsigned(11875000, 32), to_unsigned(11883333, 32), to_unsigned(11891667, 32),
     to_unsigned(11900000, 32), to_unsigned(11908333, 32), to_unsigned(11916667, 32), to_unsigned(11925000, 32),
     to_unsigned(11933333, 32), to_unsigned(11941667, 32), to_unsigned(11950000, 32), to_unsigned(11958333, 32),
     to_unsigned(11966667, 32), to_unsigned(11975000, 32), to_unsigned(11983333, 32), to_unsigned(11991667, 32),
     to_unsigned(12000000, 32), to_unsigned(12008333, 32), to_unsigned(12016667, 32), to_unsigned(12025000, 32),
     to_unsigned(12033333, 32), to_unsigned(12041667, 32), to_unsigned(12050000, 32), to_unsigned(12058333, 32),
     to_unsigned(12066667, 32), to_unsigned(12075000, 32), to_unsigned(12083333, 32), to_unsigned(12091667, 32),
     to_unsigned(12100000, 32), to_unsigned(12108333, 32), to_unsigned(12116667, 32), to_unsigned(12125000, 32),
     to_unsigned(12133333, 32), to_unsigned(12141667, 32), to_unsigned(12150000, 32), to_unsigned(12158333, 32),
     to_unsigned(12166667, 32), to_unsigned(12175000, 32), to_unsigned(12183333, 32), to_unsigned(12191667, 32),
     to_unsigned(12200000, 32), to_unsigned(12208333, 32), to_unsigned(12216667, 32), to_unsigned(12225000, 32),
     to_unsigned(12233333, 32), to_unsigned(12241667, 32), to_unsigned(12250000, 32), to_unsigned(12258333, 32),
     to_unsigned(12266667, 32), to_unsigned(12275000, 32), to_unsigned(12283333, 32), to_unsigned(12291667, 32),
     to_unsigned(12300000, 32), to_unsigned(12308333, 32), to_unsigned(12316667, 32), to_unsigned(12325000, 32),
     to_unsigned(12333333, 32), to_unsigned(12341667, 32), to_unsigned(12350000, 32), to_unsigned(12358333, 32),
     to_unsigned(12366667, 32), to_unsigned(12375000, 32), to_unsigned(12383333, 32), to_unsigned(12391667, 32),
     to_unsigned(12400000, 32), to_unsigned(12408333, 32), to_unsigned(12416667, 32), to_unsigned(12425000, 32),
     to_unsigned(12433333, 32), to_unsigned(12441667, 32), to_unsigned(12450000, 32), to_unsigned(12458333, 32),
     to_unsigned(12466667, 32), to_unsigned(12475000, 32), to_unsigned(12483333, 32), to_unsigned(12491667, 32),
     to_unsigned(12500000, 32), to_unsigned(12508333, 32), to_unsigned(12516667, 32), to_unsigned(12525000, 32),
     to_unsigned(12533333, 32), to_unsigned(12541667, 32), to_unsigned(12550000, 32), to_unsigned(12558333, 32),
     to_unsigned(12566667, 32), to_unsigned(12575000, 32), to_unsigned(12583333, 32), to_unsigned(12591667, 32),
     to_unsigned(12600000, 32), to_unsigned(12608333, 32), to_unsigned(12616667, 32), to_unsigned(12625000, 32),
     to_unsigned(12633333, 32), to_unsigned(12641667, 32), to_unsigned(12650000, 32), to_unsigned(12658333, 32),
     to_unsigned(12666667, 32), to_unsigned(12675000, 32), to_unsigned(12683333, 32), to_unsigned(12691667, 32),
     to_unsigned(12700000, 32), to_unsigned(12708333, 32), to_unsigned(12716667, 32), to_unsigned(12725000, 32),
     to_unsigned(12733333, 32), to_unsigned(12741667, 32), to_unsigned(12750000, 32), to_unsigned(12758333, 32),
     to_unsigned(12766667, 32), to_unsigned(12775000, 32), to_unsigned(12783333, 32), to_unsigned(12791667, 32),
     to_unsigned(12800000, 32), to_unsigned(12808333, 32), to_unsigned(12816667, 32), to_unsigned(12825000, 32),
     to_unsigned(12833333, 32), to_unsigned(12841667, 32), to_unsigned(12850000, 32), to_unsigned(12858333, 32),
     to_unsigned(12866667, 32), to_unsigned(12875000, 32), to_unsigned(12883333, 32), to_unsigned(12891667, 32),
     to_unsigned(12900000, 32), to_unsigned(12908333, 32), to_unsigned(12916667, 32), to_unsigned(12925000, 32),
     to_unsigned(12933333, 32), to_unsigned(12941667, 32), to_unsigned(12950000, 32), to_unsigned(12958333, 32),
     to_unsigned(12966667, 32), to_unsigned(12975000, 32), to_unsigned(12983333, 32), to_unsigned(12991667, 32),
     to_unsigned(13000000, 32), to_unsigned(13008333, 32), to_unsigned(13016667, 32), to_unsigned(13025000, 32),
     to_unsigned(13033333, 32), to_unsigned(13041667, 32), to_unsigned(13050000, 32), to_unsigned(13058333, 32),
     to_unsigned(13066667, 32), to_unsigned(13075000, 32), to_unsigned(13083333, 32), to_unsigned(13091667, 32),
     to_unsigned(13100000, 32), to_unsigned(13108333, 32), to_unsigned(13116667, 32), to_unsigned(13125000, 32),
     to_unsigned(13133333, 32), to_unsigned(13141667, 32), to_unsigned(13150000, 32), to_unsigned(13158333, 32),
     to_unsigned(13166667, 32), to_unsigned(13175000, 32), to_unsigned(13183333, 32), to_unsigned(13191667, 32),
     to_unsigned(13200000, 32), to_unsigned(13208333, 32), to_unsigned(13216667, 32), to_unsigned(13225000, 32),
     to_unsigned(13233333, 32), to_unsigned(13241667, 32), to_unsigned(13250000, 32), to_unsigned(13258333, 32),
     to_unsigned(13266667, 32), to_unsigned(13275000, 32), to_unsigned(13283333, 32), to_unsigned(13291667, 32),
     to_unsigned(13300000, 32), to_unsigned(13308333, 32), to_unsigned(13316667, 32), to_unsigned(13325000, 32),
     to_unsigned(13333333, 32), to_unsigned(13341667, 32), to_unsigned(13350000, 32), to_unsigned(13358333, 32),
     to_unsigned(13366667, 32), to_unsigned(13375000, 32), to_unsigned(13383333, 32), to_unsigned(13391667, 32),
     to_unsigned(13400000, 32), to_unsigned(13408333, 32), to_unsigned(13416667, 32), to_unsigned(13425000, 32),
     to_unsigned(13433333, 32), to_unsigned(13441667, 32), to_unsigned(13450000, 32), to_unsigned(13458333, 32),
     to_unsigned(13466667, 32), to_unsigned(13475000, 32), to_unsigned(13483333, 32), to_unsigned(13491667, 32),
     to_unsigned(13500000, 32), to_unsigned(13508333, 32), to_unsigned(13516667, 32), to_unsigned(13525000, 32),
     to_unsigned(13533333, 32), to_unsigned(13541667, 32), to_unsigned(13550000, 32), to_unsigned(13558333, 32),
     to_unsigned(13566667, 32), to_unsigned(13575000, 32), to_unsigned(13583333, 32), to_unsigned(13591667, 32),
     to_unsigned(13600000, 32), to_unsigned(13608333, 32), to_unsigned(13616667, 32), to_unsigned(13625000, 32),
     to_unsigned(13633333, 32), to_unsigned(13641667, 32), to_unsigned(13650000, 32), to_unsigned(13658333, 32),
     to_unsigned(13666667, 32), to_unsigned(13675000, 32), to_unsigned(13683333, 32), to_unsigned(13691667, 32),
     to_unsigned(13700000, 32), to_unsigned(13708333, 32), to_unsigned(13716667, 32), to_unsigned(13725000, 32),
     to_unsigned(13733333, 32), to_unsigned(13741667, 32), to_unsigned(13750000, 32), to_unsigned(13758333, 32),
     to_unsigned(13766667, 32), to_unsigned(13775000, 32), to_unsigned(13783333, 32), to_unsigned(13791667, 32),
     to_unsigned(13800000, 32), to_unsigned(13808333, 32), to_unsigned(13816667, 32), to_unsigned(13825000, 32),
     to_unsigned(13833333, 32), to_unsigned(13841667, 32), to_unsigned(13850000, 32), to_unsigned(13858333, 32),
     to_unsigned(13866667, 32), to_unsigned(13875000, 32), to_unsigned(13883333, 32), to_unsigned(13891667, 32),
     to_unsigned(13900000, 32), to_unsigned(13908333, 32), to_unsigned(13916667, 32), to_unsigned(13925000, 32),
     to_unsigned(13933333, 32), to_unsigned(13941667, 32), to_unsigned(13950000, 32), to_unsigned(13958333, 32),
     to_unsigned(13966667, 32), to_unsigned(13975000, 32), to_unsigned(13983333, 32), to_unsigned(13991667, 32),
     to_unsigned(14000000, 32), to_unsigned(14008333, 32), to_unsigned(14016667, 32), to_unsigned(14025000, 32),
     to_unsigned(14033333, 32), to_unsigned(14041667, 32), to_unsigned(14050000, 32), to_unsigned(14058333, 32),
     to_unsigned(14066667, 32), to_unsigned(14075000, 32), to_unsigned(14083333, 32), to_unsigned(14091667, 32),
     to_unsigned(14100000, 32), to_unsigned(14108333, 32), to_unsigned(14116667, 32), to_unsigned(14125000, 32),
     to_unsigned(14133333, 32), to_unsigned(14141667, 32), to_unsigned(14150000, 32), to_unsigned(14158333, 32),
     to_unsigned(14166667, 32), to_unsigned(14175000, 32), to_unsigned(14183333, 32), to_unsigned(14191667, 32),
     to_unsigned(14200000, 32), to_unsigned(14208333, 32), to_unsigned(14216667, 32), to_unsigned(14225000, 32),
     to_unsigned(14233333, 32), to_unsigned(14241667, 32), to_unsigned(14250000, 32), to_unsigned(14258333, 32),
     to_unsigned(14266667, 32), to_unsigned(14275000, 32), to_unsigned(14283333, 32), to_unsigned(14291667, 32),
     to_unsigned(14300000, 32), to_unsigned(14308333, 32), to_unsigned(14316667, 32), to_unsigned(14325000, 32),
     to_unsigned(14333333, 32), to_unsigned(14341667, 32), to_unsigned(14350000, 32), to_unsigned(14358333, 32),
     to_unsigned(14366667, 32), to_unsigned(14375000, 32), to_unsigned(14383333, 32), to_unsigned(14391667, 32),
     to_unsigned(14400000, 32), to_unsigned(14408333, 32), to_unsigned(14416667, 32), to_unsigned(14425000, 32),
     to_unsigned(14433333, 32), to_unsigned(14441667, 32), to_unsigned(14450000, 32), to_unsigned(14458333, 32),
     to_unsigned(14466667, 32), to_unsigned(14475000, 32), to_unsigned(14483333, 32), to_unsigned(14491667, 32),
     to_unsigned(14500000, 32), to_unsigned(14508333, 32), to_unsigned(14516667, 32), to_unsigned(14525000, 32),
     to_unsigned(14533333, 32), to_unsigned(14541667, 32), to_unsigned(14550000, 32), to_unsigned(14558333, 32),
     to_unsigned(14566667, 32), to_unsigned(14575000, 32), to_unsigned(14583333, 32), to_unsigned(14591667, 32),
     to_unsigned(14600000, 32), to_unsigned(14608333, 32), to_unsigned(14616667, 32), to_unsigned(14625000, 32),
     to_unsigned(14633333, 32), to_unsigned(14641667, 32), to_unsigned(14650000, 32), to_unsigned(14658333, 32),
     to_unsigned(14666667, 32), to_unsigned(14675000, 32), to_unsigned(14683333, 32), to_unsigned(14691667, 32),
     to_unsigned(14700000, 32), to_unsigned(14708333, 32), to_unsigned(14716667, 32), to_unsigned(14725000, 32),
     to_unsigned(14733333, 32), to_unsigned(14741667, 32), to_unsigned(14750000, 32), to_unsigned(14758333, 32),
     to_unsigned(14766667, 32), to_unsigned(14775000, 32), to_unsigned(14783333, 32), to_unsigned(14791667, 32),
     to_unsigned(14800000, 32), to_unsigned(14808333, 32), to_unsigned(14816667, 32), to_unsigned(14825000, 32),
     to_unsigned(14833333, 32), to_unsigned(14841667, 32), to_unsigned(14850000, 32), to_unsigned(14858333, 32),
     to_unsigned(14866667, 32), to_unsigned(14875000, 32), to_unsigned(14883333, 32), to_unsigned(14891667, 32),
     to_unsigned(14900000, 32), to_unsigned(14908333, 32), to_unsigned(14916667, 32), to_unsigned(14925000, 32),
     to_unsigned(14933333, 32), to_unsigned(14941667, 32), to_unsigned(14950000, 32), to_unsigned(14958333, 32),
     to_unsigned(14966667, 32), to_unsigned(14975000, 32), to_unsigned(14983333, 32), to_unsigned(14991667, 32),
     to_unsigned(15000000, 32), to_unsigned(15008333, 32), to_unsigned(15016667, 32), to_unsigned(15025000, 32),
     to_unsigned(15033333, 32), to_unsigned(15041667, 32), to_unsigned(15050000, 32), to_unsigned(15058333, 32),
     to_unsigned(15066667, 32), to_unsigned(15075000, 32), to_unsigned(15083333, 32), to_unsigned(15091667, 32),
     to_unsigned(15100000, 32), to_unsigned(15108333, 32), to_unsigned(15116667, 32), to_unsigned(15125000, 32),
     to_unsigned(15133333, 32), to_unsigned(15141667, 32), to_unsigned(15150000, 32), to_unsigned(15158333, 32),
     to_unsigned(15166667, 32), to_unsigned(15175000, 32), to_unsigned(15183333, 32), to_unsigned(15191667, 32),
     to_unsigned(15200000, 32), to_unsigned(15208333, 32), to_unsigned(15216667, 32), to_unsigned(15225000, 32),
     to_unsigned(15233333, 32), to_unsigned(15241667, 32), to_unsigned(15250000, 32), to_unsigned(15258333, 32),
     to_unsigned(15266667, 32), to_unsigned(15275000, 32), to_unsigned(15283333, 32), to_unsigned(15291667, 32),
     to_unsigned(15300000, 32), to_unsigned(15308333, 32), to_unsigned(15316667, 32), to_unsigned(15325000, 32),
     to_unsigned(15333333, 32), to_unsigned(15341667, 32), to_unsigned(15350000, 32), to_unsigned(15358333, 32),
     to_unsigned(15366667, 32), to_unsigned(15375000, 32), to_unsigned(15383333, 32), to_unsigned(15391667, 32),
     to_unsigned(15400000, 32), to_unsigned(15408333, 32), to_unsigned(15416667, 32), to_unsigned(15425000, 32),
     to_unsigned(15433333, 32), to_unsigned(15441667, 32), to_unsigned(15450000, 32), to_unsigned(15458333, 32),
     to_unsigned(15466667, 32), to_unsigned(15475000, 32), to_unsigned(15483333, 32), to_unsigned(15491667, 32),
     to_unsigned(15500000, 32), to_unsigned(15508333, 32), to_unsigned(15516667, 32), to_unsigned(15525000, 32),
     to_unsigned(15533333, 32), to_unsigned(15541667, 32), to_unsigned(15550000, 32), to_unsigned(15558333, 32),
     to_unsigned(15566667, 32), to_unsigned(15575000, 32), to_unsigned(15583333, 32), to_unsigned(15591667, 32),
     to_unsigned(15600000, 32), to_unsigned(15608333, 32), to_unsigned(15616667, 32), to_unsigned(15625000, 32),
     to_unsigned(15633333, 32), to_unsigned(15641667, 32), to_unsigned(15650000, 32), to_unsigned(15658333, 32),
     to_unsigned(15666667, 32), to_unsigned(15675000, 32), to_unsigned(15683333, 32), to_unsigned(15691667, 32),
     to_unsigned(15700000, 32), to_unsigned(15708333, 32), to_unsigned(15716667, 32), to_unsigned(15725000, 32),
     to_unsigned(15733333, 32), to_unsigned(15741667, 32), to_unsigned(15750000, 32), to_unsigned(15758333, 32),
     to_unsigned(15766667, 32), to_unsigned(15775000, 32), to_unsigned(15783333, 32), to_unsigned(15791667, 32),
     to_unsigned(15800000, 32), to_unsigned(15808333, 32), to_unsigned(15816667, 32), to_unsigned(15825000, 32),
     to_unsigned(15833333, 32), to_unsigned(15841667, 32), to_unsigned(15850000, 32), to_unsigned(15858333, 32),
     to_unsigned(15866667, 32), to_unsigned(15875000, 32), to_unsigned(15883333, 32), to_unsigned(15891667, 32),
     to_unsigned(15900000, 32), to_unsigned(15908333, 32), to_unsigned(15916667, 32), to_unsigned(15925000, 32),
     to_unsigned(15933333, 32), to_unsigned(15941667, 32), to_unsigned(15950000, 32), to_unsigned(15958333, 32),
     to_unsigned(15966667, 32), to_unsigned(15975000, 32), to_unsigned(15983333, 32), to_unsigned(15991667, 32),
     to_unsigned(16000000, 32), to_unsigned(16008333, 32), to_unsigned(16016667, 32), to_unsigned(16025000, 32),
     to_unsigned(16033333, 32), to_unsigned(16041667, 32), to_unsigned(16050000, 32), to_unsigned(16058333, 32),
     to_unsigned(16066667, 32), to_unsigned(16075000, 32), to_unsigned(16083333, 32), to_unsigned(16091667, 32),
     to_unsigned(16100000, 32), to_unsigned(16108333, 32), to_unsigned(16116667, 32), to_unsigned(16125000, 32),
     to_unsigned(16133333, 32), to_unsigned(16141667, 32), to_unsigned(16150000, 32), to_unsigned(16158333, 32),
     to_unsigned(16166667, 32), to_unsigned(16175000, 32), to_unsigned(16183333, 32), to_unsigned(16191667, 32),
     to_unsigned(16200000, 32), to_unsigned(16208333, 32), to_unsigned(16216667, 32), to_unsigned(16225000, 32),
     to_unsigned(16233333, 32), to_unsigned(16241667, 32), to_unsigned(16250000, 32), to_unsigned(16258333, 32),
     to_unsigned(16266667, 32), to_unsigned(16275000, 32), to_unsigned(16283333, 32), to_unsigned(16291667, 32),
     to_unsigned(16300000, 32), to_unsigned(16308333, 32), to_unsigned(16316667, 32), to_unsigned(16325000, 32),
     to_unsigned(16333333, 32), to_unsigned(16341667, 32), to_unsigned(16350000, 32), to_unsigned(16358333, 32),
     to_unsigned(16366667, 32), to_unsigned(16375000, 32), to_unsigned(16383333, 32), to_unsigned(16391667, 32),
     to_unsigned(16400000, 32), to_unsigned(16408333, 32), to_unsigned(16416667, 32), to_unsigned(16425000, 32),
     to_unsigned(16433333, 32), to_unsigned(16441667, 32), to_unsigned(16450000, 32), to_unsigned(16458333, 32),
     to_unsigned(16466667, 32), to_unsigned(16475000, 32), to_unsigned(16483333, 32), to_unsigned(16491667, 32),
     to_unsigned(16500000, 32), to_unsigned(16508333, 32), to_unsigned(16516667, 32), to_unsigned(16525000, 32),
     to_unsigned(16533333, 32), to_unsigned(16541667, 32), to_unsigned(16550000, 32), to_unsigned(16558333, 32),
     to_unsigned(16566667, 32), to_unsigned(16575000, 32), to_unsigned(16583333, 32), to_unsigned(16591667, 32),
     to_unsigned(16600000, 32), to_unsigned(16608333, 32), to_unsigned(16616667, 32), to_unsigned(16625000, 32),
     to_unsigned(16633333, 32), to_unsigned(16641667, 32), to_unsigned(16650000, 32), to_unsigned(16658333, 32),
     to_unsigned(16666667, 32), to_unsigned(16675000, 32), to_unsigned(16683333, 32), to_unsigned(16691667, 32),
     to_unsigned(16700000, 32), to_unsigned(16708333, 32), to_unsigned(16716667, 32), to_unsigned(16725000, 32),
     to_unsigned(16733333, 32), to_unsigned(16741667, 32), to_unsigned(16750000, 32), to_unsigned(16758333, 32),
     to_unsigned(16766667, 32), to_unsigned(16775000, 32), to_unsigned(16783333, 32), to_unsigned(16791667, 32),
     to_unsigned(16800000, 32), to_unsigned(16808333, 32), to_unsigned(16816667, 32), to_unsigned(16825000, 32),
     to_unsigned(16833333, 32), to_unsigned(16841667, 32), to_unsigned(16850000, 32), to_unsigned(16858333, 32),
     to_unsigned(16866667, 32), to_unsigned(16875000, 32), to_unsigned(16883333, 32), to_unsigned(16891667, 32),
     to_unsigned(16900000, 32), to_unsigned(16908333, 32), to_unsigned(16916667, 32), to_unsigned(16925000, 32),
     to_unsigned(16933333, 32), to_unsigned(16941667, 32), to_unsigned(16950000, 32), to_unsigned(16958333, 32),
     to_unsigned(16966667, 32), to_unsigned(16975000, 32), to_unsigned(16983333, 32), to_unsigned(16991667, 32),
     to_unsigned(17000000, 32), to_unsigned(17008333, 32), to_unsigned(17016667, 32), to_unsigned(17025000, 32),
     to_unsigned(17033333, 32), to_unsigned(17041667, 32), to_unsigned(17050000, 32), to_unsigned(17058333, 32),
     to_unsigned(17066667, 32), to_unsigned(17075000, 32), to_unsigned(17083333, 32), to_unsigned(17091667, 32),
     to_unsigned(17100000, 32), to_unsigned(17108333, 32), to_unsigned(17116667, 32), to_unsigned(17125000, 32),
     to_unsigned(17133333, 32), to_unsigned(17141667, 32), to_unsigned(17150000, 32), to_unsigned(17158333, 32),
     to_unsigned(17166667, 32), to_unsigned(17175000, 32), to_unsigned(17183333, 32), to_unsigned(17191667, 32),
     to_unsigned(17200000, 32), to_unsigned(17208333, 32), to_unsigned(17216667, 32), to_unsigned(17225000, 32),
     to_unsigned(17233333, 32), to_unsigned(17241667, 32), to_unsigned(17250000, 32), to_unsigned(17258333, 32),
     to_unsigned(17266667, 32), to_unsigned(17275000, 32), to_unsigned(17283333, 32), to_unsigned(17291667, 32),
     to_unsigned(17300000, 32), to_unsigned(17308333, 32), to_unsigned(17316667, 32), to_unsigned(17325000, 32),
     to_unsigned(17333333, 32), to_unsigned(17341667, 32), to_unsigned(17350000, 32), to_unsigned(17358333, 32),
     to_unsigned(17366667, 32), to_unsigned(17375000, 32), to_unsigned(17383333, 32), to_unsigned(17391667, 32),
     to_unsigned(17400000, 32), to_unsigned(17408333, 32), to_unsigned(17416667, 32), to_unsigned(17425000, 32),
     to_unsigned(17433333, 32), to_unsigned(17441667, 32), to_unsigned(17450000, 32), to_unsigned(17458333, 32),
     to_unsigned(17466667, 32), to_unsigned(17475000, 32), to_unsigned(17483333, 32), to_unsigned(17491667, 32),
     to_unsigned(17500000, 32), to_unsigned(17508333, 32), to_unsigned(17516667, 32), to_unsigned(17525000, 32),
     to_unsigned(17533333, 32), to_unsigned(17541667, 32), to_unsigned(17550000, 32), to_unsigned(17558333, 32),
     to_unsigned(17566667, 32), to_unsigned(17575000, 32), to_unsigned(17583333, 32), to_unsigned(17591667, 32),
     to_unsigned(17600000, 32), to_unsigned(17608333, 32), to_unsigned(17616667, 32), to_unsigned(17625000, 32),
     to_unsigned(17633333, 32), to_unsigned(17641667, 32), to_unsigned(17650000, 32), to_unsigned(17658333, 32),
     to_unsigned(17666667, 32), to_unsigned(17675000, 32), to_unsigned(17683333, 32), to_unsigned(17691667, 32),
     to_unsigned(17700000, 32), to_unsigned(17708333, 32), to_unsigned(17716667, 32), to_unsigned(17725000, 32),
     to_unsigned(17733333, 32), to_unsigned(17741667, 32), to_unsigned(17750000, 32), to_unsigned(17758333, 32),
     to_unsigned(17766667, 32), to_unsigned(17775000, 32), to_unsigned(17783333, 32), to_unsigned(17791667, 32),
     to_unsigned(17800000, 32), to_unsigned(17808333, 32), to_unsigned(17816667, 32), to_unsigned(17825000, 32),
     to_unsigned(17833333, 32), to_unsigned(17841667, 32), to_unsigned(17850000, 32), to_unsigned(17858333, 32),
     to_unsigned(17866667, 32), to_unsigned(17875000, 32), to_unsigned(17883333, 32), to_unsigned(17891667, 32),
     to_unsigned(17900000, 32), to_unsigned(17908333, 32), to_unsigned(17916667, 32), to_unsigned(17925000, 32),
     to_unsigned(17933333, 32), to_unsigned(17941667, 32), to_unsigned(17950000, 32), to_unsigned(17958333, 32),
     to_unsigned(17966667, 32), to_unsigned(17975000, 32), to_unsigned(17983333, 32), to_unsigned(17991667, 32),
     to_unsigned(18000000, 32), to_unsigned(18008333, 32), to_unsigned(18016667, 32), to_unsigned(18025000, 32),
     to_unsigned(18033333, 32), to_unsigned(18041667, 32), to_unsigned(18050000, 32), to_unsigned(18058333, 32),
     to_unsigned(18066667, 32), to_unsigned(18075000, 32), to_unsigned(18083333, 32), to_unsigned(18091667, 32),
     to_unsigned(18100000, 32), to_unsigned(18108333, 32), to_unsigned(18116667, 32), to_unsigned(18125000, 32),
     to_unsigned(18133333, 32), to_unsigned(18141667, 32), to_unsigned(18150000, 32), to_unsigned(18158333, 32),
     to_unsigned(18166667, 32), to_unsigned(18175000, 32), to_unsigned(18183333, 32), to_unsigned(18191667, 32),
     to_unsigned(18200000, 32), to_unsigned(18208333, 32), to_unsigned(18216667, 32), to_unsigned(18225000, 32),
     to_unsigned(18233333, 32), to_unsigned(18241667, 32), to_unsigned(18250000, 32), to_unsigned(18258333, 32),
     to_unsigned(18266667, 32), to_unsigned(18275000, 32), to_unsigned(18283333, 32), to_unsigned(18291667, 32),
     to_unsigned(18300000, 32), to_unsigned(18308333, 32), to_unsigned(18316667, 32), to_unsigned(18325000, 32),
     to_unsigned(18333333, 32), to_unsigned(18341667, 32), to_unsigned(18350000, 32), to_unsigned(18358333, 32),
     to_unsigned(18366667, 32), to_unsigned(18375000, 32), to_unsigned(18383333, 32), to_unsigned(18391667, 32),
     to_unsigned(18400000, 32), to_unsigned(18408333, 32), to_unsigned(18416667, 32), to_unsigned(18425000, 32),
     to_unsigned(18433333, 32), to_unsigned(18441667, 32), to_unsigned(18450000, 32), to_unsigned(18458333, 32),
     to_unsigned(18466667, 32), to_unsigned(18475000, 32), to_unsigned(18483333, 32), to_unsigned(18491667, 32),
     to_unsigned(18500000, 32), to_unsigned(18508333, 32), to_unsigned(18516667, 32), to_unsigned(18525000, 32),
     to_unsigned(18533333, 32), to_unsigned(18541667, 32), to_unsigned(18550000, 32), to_unsigned(18558333, 32),
     to_unsigned(18566667, 32), to_unsigned(18575000, 32), to_unsigned(18583333, 32), to_unsigned(18591667, 32),
     to_unsigned(18600000, 32), to_unsigned(18608333, 32), to_unsigned(18616667, 32), to_unsigned(18625000, 32),
     to_unsigned(18633333, 32), to_unsigned(18641667, 32), to_unsigned(18650000, 32), to_unsigned(18658333, 32),
     to_unsigned(18666667, 32), to_unsigned(18675000, 32), to_unsigned(18683333, 32), to_unsigned(18691667, 32),
     to_unsigned(18700000, 32), to_unsigned(18708333, 32), to_unsigned(18716667, 32), to_unsigned(18725000, 32),
     to_unsigned(18733333, 32), to_unsigned(18741667, 32), to_unsigned(18750000, 32), to_unsigned(18758333, 32),
     to_unsigned(18766667, 32), to_unsigned(18775000, 32), to_unsigned(18783333, 32), to_unsigned(18791667, 32),
     to_unsigned(18800000, 32), to_unsigned(18808333, 32), to_unsigned(18816667, 32), to_unsigned(18825000, 32),
     to_unsigned(18833333, 32), to_unsigned(18841667, 32), to_unsigned(18850000, 32), to_unsigned(18858333, 32),
     to_unsigned(18866667, 32), to_unsigned(18875000, 32), to_unsigned(18883333, 32), to_unsigned(18891667, 32),
     to_unsigned(18900000, 32), to_unsigned(18908333, 32), to_unsigned(18916667, 32), to_unsigned(18925000, 32),
     to_unsigned(18933333, 32), to_unsigned(18941667, 32), to_unsigned(18950000, 32), to_unsigned(18958333, 32),
     to_unsigned(18966667, 32), to_unsigned(18975000, 32), to_unsigned(18983333, 32), to_unsigned(18991667, 32),
     to_unsigned(19000000, 32), to_unsigned(19008333, 32), to_unsigned(19016667, 32), to_unsigned(19025000, 32),
     to_unsigned(19033333, 32), to_unsigned(19041667, 32), to_unsigned(19050000, 32), to_unsigned(19058333, 32),
     to_unsigned(19066667, 32), to_unsigned(19075000, 32), to_unsigned(19083333, 32), to_unsigned(19091667, 32),
     to_unsigned(19100000, 32), to_unsigned(19108333, 32), to_unsigned(19116667, 32), to_unsigned(19125000, 32),
     to_unsigned(19133333, 32), to_unsigned(19141667, 32), to_unsigned(19150000, 32), to_unsigned(19158333, 32),
     to_unsigned(19166667, 32), to_unsigned(19175000, 32), to_unsigned(19183333, 32), to_unsigned(19191667, 32),
     to_unsigned(19200000, 32), to_unsigned(19208333, 32), to_unsigned(19216667, 32), to_unsigned(19225000, 32),
     to_unsigned(19233333, 32), to_unsigned(19241667, 32), to_unsigned(19250000, 32), to_unsigned(19258333, 32),
     to_unsigned(19266667, 32), to_unsigned(19275000, 32), to_unsigned(19283333, 32), to_unsigned(19291667, 32),
     to_unsigned(19300000, 32), to_unsigned(19308333, 32), to_unsigned(19316667, 32), to_unsigned(19325000, 32),
     to_unsigned(19333333, 32), to_unsigned(19341667, 32), to_unsigned(19350000, 32), to_unsigned(19358333, 32),
     to_unsigned(19366667, 32), to_unsigned(19375000, 32), to_unsigned(19383333, 32), to_unsigned(19391667, 32),
     to_unsigned(19400000, 32), to_unsigned(19408333, 32), to_unsigned(19416667, 32), to_unsigned(19425000, 32),
     to_unsigned(19433333, 32), to_unsigned(19441667, 32), to_unsigned(19450000, 32), to_unsigned(19458333, 32),
     to_unsigned(19466667, 32), to_unsigned(19475000, 32), to_unsigned(19483333, 32), to_unsigned(19491667, 32),
     to_unsigned(19500000, 32), to_unsigned(19508333, 32), to_unsigned(19516667, 32), to_unsigned(19525000, 32),
     to_unsigned(19533333, 32), to_unsigned(19541667, 32), to_unsigned(19550000, 32), to_unsigned(19558333, 32),
     to_unsigned(19566667, 32), to_unsigned(19575000, 32), to_unsigned(19583333, 32), to_unsigned(19591667, 32),
     to_unsigned(19600000, 32), to_unsigned(19608333, 32), to_unsigned(19616667, 32), to_unsigned(19625000, 32),
     to_unsigned(19633333, 32), to_unsigned(19641667, 32), to_unsigned(19650000, 32), to_unsigned(19658333, 32),
     to_unsigned(19666667, 32), to_unsigned(19675000, 32), to_unsigned(19683333, 32), to_unsigned(19691667, 32),
     to_unsigned(19700000, 32), to_unsigned(19708333, 32), to_unsigned(19716667, 32), to_unsigned(19725000, 32),
     to_unsigned(19733333, 32), to_unsigned(19741667, 32), to_unsigned(19750000, 32), to_unsigned(19758333, 32),
     to_unsigned(19766667, 32), to_unsigned(19775000, 32), to_unsigned(19783333, 32), to_unsigned(19791667, 32),
     to_unsigned(19800000, 32), to_unsigned(19808333, 32), to_unsigned(19816667, 32), to_unsigned(19825000, 32),
     to_unsigned(19833333, 32), to_unsigned(19841667, 32), to_unsigned(19850000, 32), to_unsigned(19858333, 32),
     to_unsigned(19866667, 32), to_unsigned(19875000, 32), to_unsigned(19883333, 32), to_unsigned(19891667, 32),
     to_unsigned(19900000, 32), to_unsigned(19908333, 32), to_unsigned(19916667, 32), to_unsigned(19925000, 32),
     to_unsigned(19933333, 32), to_unsigned(19941667, 32), to_unsigned(19950000, 32), to_unsigned(19958333, 32),
     to_unsigned(19966667, 32), to_unsigned(19975000, 32), to_unsigned(19983333, 32), to_unsigned(19991667, 32),
     to_unsigned(20000000, 32));  -- ufix32 [1201]

  -- Signals
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- ufix16_En10
  SIGNAL Counter_Limited_out1             : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Counter_Limited_out1_unsigned    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL alpha1_D_Lookup_Table1_k         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL alpha1_D_Lookup_Table1_out1      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL alpha1_D_Lookup_Table1_out1_1    : unsigned(31 DOWNTO 0) := to_unsigned(0, 32);  -- uint32
  SIGNAL Product_mul_temp                 : unsigned(47 DOWNTO 0);  -- ufix48_En10
  SIGNAL Product_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL NCO1_out1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Counter_Limited : Counter_Limited
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              y => Counter_Limited_out1  -- uint8
              );

  u_NCO1 : NCO1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              inc => std_logic_vector(Product_out1),  -- uint32
              validIn => valid,
              cosine => NCO1_out1  -- sfix16_En14
              );

  Constant_out1 <= to_unsigned(16#8F2A#, 16);

  Counter_Limited_out1_unsigned <= unsigned(Counter_Limited_out1);

  
  alpha1_D_Lookup_Table1_k <= to_unsigned(16#000#, 11) WHEN resize(Counter_Limited_out1_unsigned, 16) = to_unsigned(16#0000#, 16) ELSE
      resize(Counter_Limited_out1_unsigned, 11);
  alpha1_D_Lookup_Table1_out1 <= alpha1_D_Lookup_Table1_data(to_integer(alpha1_D_Lookup_Table1_k));

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha1_D_Lookup_Table1_out1_1 <= alpha1_D_Lookup_Table1_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  Product_mul_temp <= Constant_out1 * alpha1_D_Lookup_Table1_out1_1;
  Product_out1 <= Product_mul_temp(41 DOWNTO 10);

  X <= NCO1_out1;

END rtl;

