-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ddc_simulink_CRD_fixed\Increment_Real_World.vhd
-- Created: 2025-11-17 12:04:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Increment_Real_World
-- Source Path: ddc_simulink_CRD_fixed/Chirp/Counter Limited/Increment Real World
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Increment_Real_World IS
  PORT( u                                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        y                                 :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END Increment_Real_World;


ARCHITECTURE rtl OF Increment_Real_World IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL FixPt_Constant_out1              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL FixPt_Sum1_out1                  : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_unsigned <= unsigned(u);

  FixPt_Constant_out1 <= to_unsigned(16#01#, 8);

  FixPt_Sum1_out1 <= resize(resize(u_unsigned, 32) + resize(FixPt_Constant_out1, 32), 8);

  y <= std_logic_vector(FixPt_Sum1_out1);

END rtl;

