-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ddc_simulink_CRD_fixed\LPF.vhd
-- Created: 2025-11-17 12:04:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LPF
-- Source Path: ddc_simulink_CRD_fixed/LPF
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LPF IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En16
        );
END LPF;


ARCHITECTURE rtl OF LPF IS

  -- Signals
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay_out1                       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay2_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay3_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay4_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay5_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay6_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay7_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay8_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay9_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay10_out1                     : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay11_out1                     : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay12_out1                     : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay13_out1                     : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay14_out1                     : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant14_out1                  : signed(15 DOWNTO 0);  -- sfix16_En25
  SIGNAL Constant13_out1                  : signed(15 DOWNTO 0);  -- sfix16_En22
  SIGNAL Constant12_out1                  : signed(15 DOWNTO 0);  -- sfix16_En21
  SIGNAL Constant11_out1                  : unsigned(15 DOWNTO 0);  -- ufix16_En23
  SIGNAL Constant10_out1                  : unsigned(15 DOWNTO 0);  -- ufix16_En19
  SIGNAL Constant9_out1                   : unsigned(15 DOWNTO 0);  -- ufix16_En18
  SIGNAL Constant8_out1                   : unsigned(15 DOWNTO 0);  -- ufix16_En17
  SIGNAL Constant7_out1                   : unsigned(15 DOWNTO 0);  -- ufix16_En17
  SIGNAL Constant6_out1                   : unsigned(15 DOWNTO 0);  -- ufix16_En18
  SIGNAL Constant5_out1                   : unsigned(15 DOWNTO 0);  -- ufix16_En19
  SIGNAL Constant4_out1                   : unsigned(15 DOWNTO 0);  -- ufix16_En23
  SIGNAL Constant3_out1                   : signed(15 DOWNTO 0);  -- sfix16_En21
  SIGNAL Constant2_out1                   : signed(15 DOWNTO 0);  -- sfix16_En22
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- sfix16_En25
  SIGNAL Product1_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En39
  SIGNAL Product1_out1                    : signed(15 DOWNTO 0);  -- sfix16_En25
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- sfix16_En4
  SIGNAL Constant15_out1                  : signed(15 DOWNTO 0);  -- sfix16_En4
  SIGNAL Product15_mul_temp               : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Product15_out1                   : signed(15 DOWNTO 0);  -- sfix16_En4
  SIGNAL Product14_mul_temp               : signed(31 DOWNTO 0);  -- sfix32_En39
  SIGNAL Product14_out1                   : signed(15 DOWNTO 0);  -- sfix16_En25
  SIGNAL Product13_mul_temp               : signed(31 DOWNTO 0);  -- sfix32_En36
  SIGNAL Product13_out1                   : signed(15 DOWNTO 0);  -- sfix16_En22
  SIGNAL Product12_mul_temp               : signed(31 DOWNTO 0);  -- sfix32_En35
  SIGNAL Product12_out1                   : signed(15 DOWNTO 0);  -- sfix16_En21
  SIGNAL Product11_cast                   : signed(16 DOWNTO 0);  -- sfix17_En23
  SIGNAL Product11_mul_temp               : signed(32 DOWNTO 0);  -- sfix33_En37
  SIGNAL Product11_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En37
  SIGNAL Product11_out1                   : signed(15 DOWNTO 0);  -- sfix16_En22
  SIGNAL Product10_cast                   : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL Product10_mul_temp               : signed(32 DOWNTO 0);  -- sfix33_En33
  SIGNAL Product10_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En33
  SIGNAL Product10_out1                   : signed(15 DOWNTO 0);  -- sfix16_En18
  SIGNAL Product9_cast                    : signed(16 DOWNTO 0);  -- sfix17_En18
  SIGNAL Product9_mul_temp                : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL Product9_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En32
  SIGNAL Product9_out1                    : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL Product8_cast                    : signed(16 DOWNTO 0);  -- sfix17_En17
  SIGNAL Product8_mul_temp                : signed(32 DOWNTO 0);  -- sfix33_En31
  SIGNAL Product8_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En31
  SIGNAL Product8_out1                    : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Product7_cast                    : signed(16 DOWNTO 0);  -- sfix17_En17
  SIGNAL Product7_mul_temp                : signed(32 DOWNTO 0);  -- sfix33_En31
  SIGNAL Product7_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En31
  SIGNAL Product7_out1                    : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Product6_cast                    : signed(16 DOWNTO 0);  -- sfix17_En18
  SIGNAL Product6_mul_temp                : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL Product6_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En32
  SIGNAL Product6_out1                    : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL Product5_cast                    : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL Product5_mul_temp                : signed(32 DOWNTO 0);  -- sfix33_En33
  SIGNAL Product5_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En33
  SIGNAL Product5_out1                    : signed(15 DOWNTO 0);  -- sfix16_En18
  SIGNAL Product4_cast                    : signed(16 DOWNTO 0);  -- sfix17_En23
  SIGNAL Product4_mul_temp                : signed(32 DOWNTO 0);  -- sfix33_En37
  SIGNAL Product4_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En37
  SIGNAL Product4_out1                    : signed(15 DOWNTO 0);  -- sfix16_En22
  SIGNAL Product3_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En35
  SIGNAL Product3_out1                    : signed(15 DOWNTO 0);  -- sfix16_En21
  SIGNAL Product2_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En36
  SIGNAL Product2_out1                    : signed(15 DOWNTO 0);  -- sfix16_En22
  SIGNAL Product_mul_temp                 : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Product_out1                     : signed(15 DOWNTO 0);  -- sfix16_En4
  SIGNAL Sum_add_cast                     : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum_add_cast_1                   : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum_add_temp                     : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum_out1                         : signed(15 DOWNTO 0);  -- sfix16_En25
  SIGNAL Sum3_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum3_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum3_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum3_out1                        : signed(15 DOWNTO 0);  -- sfix16_En22
  SIGNAL Sum2_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum2_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum2_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum2_out1                        : signed(15 DOWNTO 0);  -- sfix16_En21
  SIGNAL Sum5_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum5_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum5_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum5_out1                        : signed(15 DOWNTO 0);  -- sfix16_En21
  SIGNAL Sum4_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En21
  SIGNAL Sum4_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En21
  SIGNAL Sum4_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En21
  SIGNAL Sum4_out1                        : signed(15 DOWNTO 0);  -- sfix16_En18
  SIGNAL Sum7_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Sum7_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Sum7_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Sum7_out1                        : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL Sum6_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En17
  SIGNAL Sum6_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En17
  SIGNAL Sum6_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En17
  SIGNAL Sum6_out1                        : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum9_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Sum9_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Sum9_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Sum9_out1                        : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum8_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En17
  SIGNAL Sum8_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En17
  SIGNAL Sum8_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En17
  SIGNAL Sum8_out1                        : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum11_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Sum11_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Sum11_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En18
  SIGNAL Sum11_out1                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum10_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum10_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum10_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum10_out1                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum13_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En21
  SIGNAL Sum13_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En21
  SIGNAL Sum13_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En21
  SIGNAL Sum13_out1                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum12_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum12_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum12_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL Sum12_out1                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum15_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum15_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum15_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum15_out1                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL Sum14_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Sum14_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Sum14_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Sum14_out1                       : signed(15 DOWNTO 0);  -- sfix16_En16

BEGIN
  In1_signed <= signed(In1);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= In1_signed;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Delay_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Delay1_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Delay2_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= Delay3_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= Delay4_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_out1 <= Delay5_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_out1 <= Delay6_out1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay8_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay8_out1 <= Delay7_out1;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  Delay9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay9_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay9_out1 <= Delay8_out1;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  Delay10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay10_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay10_out1 <= Delay9_out1;
      END IF;
    END IF;
  END PROCESS Delay10_process;


  Delay11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay11_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay11_out1 <= Delay10_out1;
      END IF;
    END IF;
  END PROCESS Delay11_process;


  Delay12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay12_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay12_out1 <= Delay11_out1;
      END IF;
    END IF;
  END PROCESS Delay12_process;


  Delay13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay13_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay13_out1 <= Delay12_out1;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  Delay14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay14_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay14_out1 <= Delay13_out1;
      END IF;
    END IF;
  END PROCESS Delay14_process;


  Constant14_out1 <= to_signed(-16#51B2#, 16);

  Constant13_out1 <= to_signed(-16#4A48#, 16);

  Constant12_out1 <= to_signed(-16#45E3#, 16);

  Constant11_out1 <= to_unsigned(16#F981#, 16);

  Constant10_out1 <= to_unsigned(16#9167#, 16);

  Constant9_out1 <= to_unsigned(16#B35E#, 16);

  Constant8_out1 <= to_unsigned(16#8513#, 16);

  Constant7_out1 <= to_unsigned(16#8513#, 16);

  Constant6_out1 <= to_unsigned(16#B35E#, 16);

  Constant5_out1 <= to_unsigned(16#9167#, 16);

  Constant4_out1 <= to_unsigned(16#F981#, 16);

  Constant3_out1 <= to_signed(-16#45E3#, 16);

  Constant2_out1 <= to_signed(-16#4A48#, 16);

  Constant1_out1 <= to_signed(-16#51B2#, 16);

  Product1_mul_temp <= Delay_out1 * Constant1_out1;
  Product1_out1 <= Product1_mul_temp(29 DOWNTO 14);

  Constant_out1 <= to_signed(16#0000#, 16);

  Constant15_out1 <= to_signed(16#0000#, 16);

  Product15_mul_temp <= Delay14_out1 * Constant15_out1;
  Product15_out1 <= Product15_mul_temp(29 DOWNTO 14);

  Product14_mul_temp <= Delay13_out1 * Constant14_out1;
  Product14_out1 <= Product14_mul_temp(29 DOWNTO 14);

  Product13_mul_temp <= Delay12_out1 * Constant13_out1;
  Product13_out1 <= Product13_mul_temp(29 DOWNTO 14);

  Product12_mul_temp <= Delay11_out1 * Constant12_out1;
  Product12_out1 <= Product12_mul_temp(29 DOWNTO 14);

  Product11_cast <= signed(resize(Constant11_out1, 17));
  Product11_mul_temp <= Delay10_out1 * Product11_cast;
  Product11_cast_1 <= Product11_mul_temp(31 DOWNTO 0);
  Product11_out1 <= Product11_cast_1(30 DOWNTO 15);

  Product10_cast <= signed(resize(Constant10_out1, 17));
  Product10_mul_temp <= Delay9_out1 * Product10_cast;
  Product10_cast_1 <= Product10_mul_temp(31 DOWNTO 0);
  Product10_out1 <= Product10_cast_1(30 DOWNTO 15);

  Product9_cast <= signed(resize(Constant9_out1, 17));
  Product9_mul_temp <= Delay8_out1 * Product9_cast;
  Product9_cast_1 <= Product9_mul_temp(31 DOWNTO 0);
  Product9_out1 <= Product9_cast_1(30 DOWNTO 15);

  Product8_cast <= signed(resize(Constant8_out1, 17));
  Product8_mul_temp <= Delay7_out1 * Product8_cast;
  Product8_cast_1 <= Product8_mul_temp(31 DOWNTO 0);
  Product8_out1 <= Product8_cast_1(30 DOWNTO 15);

  Product7_cast <= signed(resize(Constant7_out1, 17));
  Product7_mul_temp <= Delay6_out1 * Product7_cast;
  Product7_cast_1 <= Product7_mul_temp(31 DOWNTO 0);
  Product7_out1 <= Product7_cast_1(30 DOWNTO 15);

  Product6_cast <= signed(resize(Constant6_out1, 17));
  Product6_mul_temp <= Delay5_out1 * Product6_cast;
  Product6_cast_1 <= Product6_mul_temp(31 DOWNTO 0);
  Product6_out1 <= Product6_cast_1(30 DOWNTO 15);

  Product5_cast <= signed(resize(Constant5_out1, 17));
  Product5_mul_temp <= Delay4_out1 * Product5_cast;
  Product5_cast_1 <= Product5_mul_temp(31 DOWNTO 0);
  Product5_out1 <= Product5_cast_1(30 DOWNTO 15);

  Product4_cast <= signed(resize(Constant4_out1, 17));
  Product4_mul_temp <= Delay3_out1 * Product4_cast;
  Product4_cast_1 <= Product4_mul_temp(31 DOWNTO 0);
  Product4_out1 <= Product4_cast_1(30 DOWNTO 15);

  Product3_mul_temp <= Delay2_out1 * Constant3_out1;
  Product3_out1 <= Product3_mul_temp(29 DOWNTO 14);

  Product2_mul_temp <= Delay1_out1 * Constant2_out1;
  Product2_out1 <= Product2_mul_temp(29 DOWNTO 14);

  Product_mul_temp <= In1_signed * Constant_out1;
  Product_out1 <= Product_mul_temp(29 DOWNTO 14);

  Sum_add_cast <= resize(Product1_out1, 32);
  Sum_add_cast_1 <= Product_out1(10 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  Sum_add_temp <= Sum_add_cast + Sum_add_cast_1;
  Sum_out1 <= Sum_add_temp(15 DOWNTO 0);

  Sum3_add_cast <= resize(Product2_out1 & '0' & '0' & '0', 32);
  Sum3_add_cast_1 <= resize(Sum_out1, 32);
  Sum3_add_temp <= Sum3_add_cast + Sum3_add_cast_1;
  Sum3_out1 <= Sum3_add_temp(18 DOWNTO 3);

  Sum2_add_cast <= resize(Product3_out1 & '0', 32);
  Sum2_add_cast_1 <= resize(Sum3_out1, 32);
  Sum2_add_temp <= Sum2_add_cast + Sum2_add_cast_1;
  Sum2_out1 <= Sum2_add_temp(16 DOWNTO 1);

  Sum5_add_cast <= resize(Product4_out1, 32);
  Sum5_add_cast_1 <= resize(Sum2_out1 & '0', 32);
  Sum5_add_temp <= Sum5_add_cast + Sum5_add_cast_1;
  Sum5_out1 <= Sum5_add_temp(16 DOWNTO 1);

  Sum4_add_cast <= resize(Product5_out1 & '0' & '0' & '0', 32);
  Sum4_add_cast_1 <= resize(Sum5_out1, 32);
  Sum4_add_temp <= Sum4_add_cast + Sum4_add_cast_1;
  Sum4_out1 <= Sum4_add_temp(18 DOWNTO 3);

  Sum7_add_cast <= resize(Product6_out1 & '0', 32);
  Sum7_add_cast_1 <= resize(Sum4_out1, 32);
  Sum7_add_temp <= Sum7_add_cast + Sum7_add_cast_1;
  Sum7_out1 <= Sum7_add_temp(16 DOWNTO 1);

  Sum6_add_cast <= resize(Product7_out1 & '0', 32);
  Sum6_add_cast_1 <= resize(Sum7_out1, 32);
  Sum6_add_temp <= Sum6_add_cast + Sum6_add_cast_1;
  Sum6_out1 <= Sum6_add_temp(16 DOWNTO 1);

  Sum9_add_cast <= resize(Product8_out1, 32);
  Sum9_add_cast_1 <= resize(Sum6_out1, 32);
  Sum9_add_temp <= Sum9_add_cast + Sum9_add_cast_1;
  Sum9_out1 <= Sum9_add_temp(15 DOWNTO 0);

  Sum8_add_cast <= resize(Product9_out1, 32);
  Sum8_add_cast_1 <= resize(Sum9_out1 & '0', 32);
  Sum8_add_temp <= Sum8_add_cast + Sum8_add_cast_1;
  Sum8_out1 <= Sum8_add_temp(16 DOWNTO 1);

  Sum11_add_cast <= resize(Product10_out1, 32);
  Sum11_add_cast_1 <= resize(Sum8_out1 & '0' & '0', 32);
  Sum11_add_temp <= Sum11_add_cast + Sum11_add_cast_1;
  Sum11_out1 <= Sum11_add_temp(17 DOWNTO 2);

  Sum10_add_cast <= resize(Product11_out1, 32);
  Sum10_add_cast_1 <= resize(Sum11_out1 & '0' & '0' & '0' & '0' & '0' & '0', 32);
  Sum10_add_temp <= Sum10_add_cast + Sum10_add_cast_1;
  Sum10_out1 <= Sum10_add_temp(21 DOWNTO 6);

  Sum13_add_cast <= resize(Product12_out1, 32);
  Sum13_add_cast_1 <= resize(Sum10_out1 & '0' & '0' & '0' & '0' & '0', 32);
  Sum13_add_temp <= Sum13_add_cast + Sum13_add_cast_1;
  Sum13_out1 <= Sum13_add_temp(20 DOWNTO 5);

  Sum12_add_cast <= resize(Product13_out1, 32);
  Sum12_add_cast_1 <= resize(Sum13_out1 & '0' & '0' & '0' & '0' & '0' & '0', 32);
  Sum12_add_temp <= Sum12_add_cast + Sum12_add_cast_1;
  Sum12_out1 <= Sum12_add_temp(21 DOWNTO 6);

  Sum15_add_cast <= resize(Product14_out1, 32);
  Sum15_add_cast_1 <= resize(Sum12_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
  Sum15_add_temp <= Sum15_add_cast + Sum15_add_cast_1;
  Sum15_out1 <= Sum15_add_temp(24 DOWNTO 9);

  Sum14_add_cast <= resize(Product15_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
  Sum14_add_cast_1 <= resize(Sum15_out1, 32);
  Sum14_add_temp <= Sum14_add_cast + Sum14_add_cast_1;
  Sum14_out1 <= Sum14_add_temp(15 DOWNTO 0);

  Out1 <= std_logic_vector(Sum14_out1);

END rtl;

