-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ddc_simulink_CRD_fixed\Wrap_To_Zero.vhd
-- Created: 2025-11-17 12:04:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Wrap_To_Zero
-- Source Path: ddc_simulink_CRD_fixed/Chirp/Counter Limited/Wrap To Zero
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Wrap_To_Zero IS
  PORT( U                                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Y                                 :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END Wrap_To_Zero;


ARCHITECTURE rtl OF Wrap_To_Zero IS

  -- Signals
  SIGNAL U_unsigned                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL FixPt_Switch_out1                : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  -- U(k)

  U_unsigned <= unsigned(U);

  
  switch_compare_1 <= '1' WHEN U_unsigned > to_unsigned(16#00#, 8) ELSE
      '0';

  Constant_out1 <= to_unsigned(16#00#, 8);

  
  FixPt_Switch_out1 <= U_unsigned WHEN switch_compare_1 = '0' ELSE
      Constant_out1;

  Y <= std_logic_vector(FixPt_Switch_out1);

END rtl;

