function hdlverifier_gendll_Subsystem
% hdlverifier_gendll_Subsystem is a MATLAB calling wrapper for compiling/elaborating the HDL design
% Generated by Cosimulation Wizard on 2025-12-01 10:49:56

% ---- set path info for Vivado executables and kernel libs
lutils('PathPrepend', 'PATH', 'C:\Xilinx\Vivado\2024.1\bin\..\lib\win64.o');
lutils('PathPrepend', 'PATH', 'C:\Xilinx\Vivado\2024.1\bin');

% ---- make system call to Vivado script
[s, r] = system(['vivado -mode tcl < hdlverifier_gendll.tcl'],'-echo');

if (s ~= 0)
    error(message('HDLLink:CosimWizard:ElaborationFailed',r));
end
