function hdlverifier_compile
% hdlverifier_compile is a MATLAB calling wrapper for compiling/elaborating the HDL design
% Generated by Cosimulation Wizard on 2025-12-01 10:48:29

% ---- set path info for Vivado executables and kernel libs
lutils('PathPrepend', 'PATH', 'C:\Xilinx\Vivado\2024.1\bin\..\lib\win64.o');
lutils('PathPrepend', 'PATH', 'C:\Xilinx\Vivado\2024.1\bin');

% ---- make system call to Vivado script
[s, r] = system(['vivado -mode tcl < hdlverifier_compile.tcl'],'-echo');

if (s ~= 0)
    error(message('HDLLink:CosimWizard:CompilationError',r));
end
