-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_v2\hdlsrc\spec_avg_CRD\NCO1.vhd
-- Created: 2025-12-01 14:06:11
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: NCO1
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/DDC/Chirp/NCO1
-- Hierarchy Level: 3
-- Model version: 7.329
-- 
-- NCO
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY NCO1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        inc                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        validIn                           :   IN    std_logic;
        cosine                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validOut                          :   OUT   std_logic
        );
END NCO1;


ARCHITECTURE rtl OF NCO1 IS

  -- Component Declarations
  COMPONENT DitherGen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          validIn                         :   IN    std_logic;
          dither                          :   OUT   std_logic_vector(17 DOWNTO 0)  -- ufix18
          );
  END COMPONENT;

  COMPONENT WaveformGen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          phaseIdx                        :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13_E18
          cosine                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : DitherGen
    USE ENTITY work.DitherGen(rtl);

  FOR ALL : WaveformGen
    USE ENTITY work.WaveformGen(rtl);

  -- Signals
  SIGNAL outsel_reg_reg                   : std_logic_vector(4 DOWNTO 0);  -- ufix1 [5]
  SIGNAL outsel                           : std_logic;
  SIGNAL outzero                          : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL const0                           : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL inc_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pInc                             : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL validPInc                        : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL accphase_reg                     : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL addpInc                          : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL pOffset                          : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL accoffset                        : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL accoffsete_reg                   : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL dither                           : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL dither_unsigned                  : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL casteddither                     : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL dither_reg                       : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL accumulator                      : signed(30 DOWNTO 0);  -- sfix31
  SIGNAL accQuantized                     : unsigned(12 DOWNTO 0);  -- ufix13_E18
  SIGNAL outs                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL outs_signed                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL validouts                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL cosine_tmp                       : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_dither_inst : DitherGen
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              validIn => validIn,
              dither => dither  -- ufix18
              );

  u_Wave_inst : WaveformGen
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              phaseIdx => std_logic_vector(accQuantized),  -- ufix13_E18
              cosine => outs  -- sfix16_En14
              );

  outsel_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      outsel_reg_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        outsel_reg_reg(0) <= validIn;
        outsel_reg_reg(4 DOWNTO 1) <= outsel_reg_reg(3 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS outsel_reg_process;

  outsel <= outsel_reg_reg(4);

  outzero <= to_signed(16#0000#, 16);

  -- Constant Zero
  const0 <= to_signed(16#00000000#, 31);

  inc_unsigned <= unsigned(inc);

  pInc <= signed(inc_unsigned(30 DOWNTO 0));

  
  validPInc <= const0 WHEN validIn = '0' ELSE
      pInc;

  -- Add phase increment
  addpInc <= accphase_reg + validPInc;

  -- Phase increment accumulator register
  AccPhaseRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accphase_reg <= to_signed(16#00000000#, 31);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        accphase_reg <= addpInc;
      END IF;
    END IF;
  END PROCESS AccPhaseRegister_process;


  pOffset <= to_signed(16#20000000#, 31);

  -- Add phase offset
  accoffset <= accphase_reg + pOffset;

  -- Phase offset accumulator register
  AccOffsetRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accoffsete_reg <= to_signed(16#00000000#, 31);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        accoffsete_reg <= accoffset;
      END IF;
    END IF;
  END PROCESS AccOffsetRegister_process;


  dither_unsigned <= unsigned(dither);

  casteddither <= signed(resize(dither_unsigned, 31));

  -- Dither input register
  DitherRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dither_reg <= to_signed(16#00000000#, 31);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dither_reg <= casteddither;
      END IF;
    END IF;
  END PROCESS DitherRegister_process;


  -- Add dither
  accumulator <= accoffsete_reg + dither_reg;

  -- Phase quantization
  accQuantized <= unsigned(accumulator(30 DOWNTO 18));

  outs_signed <= signed(outs);

  
  validouts <= outzero WHEN outsel = '0' ELSE
      outs_signed;

  -- Output register
  OutputRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cosine_tmp <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        cosine_tmp <= validouts;
      END IF;
    END IF;
  END PROCESS OutputRegister_process;


  cosine <= std_logic_vector(cosine_tmp);

  -- validOut register
  validOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validOut <= outsel;
      END IF;
    END IF;
  END PROCESS validOut_reg_process;


END rtl;

