-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_v2\hdlsrc\spec_avg_CRD\Spectral_Averager.vhd
-- Created: 2025-12-01 14:06:11
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Spectral_Averager
-- Source Path: spec_avg_CRD/Digital Spectrometer from Chirp DDC/Digital Spectrometer/Spectral Averager
-- Hierarchy Level: 2
-- Model version: 7.329
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Digital_Spectrometer_from_Chirp_DDC_pkg.ALL;

ENTITY Spectral_Averager IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        signal_in                         :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
        valid_in                          :   IN    std_logic;
        avg_out                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En4
        valid_out                         :   OUT   std_logic
        );
END Spectral_Averager;


ARCHITECTURE rtl OF Spectral_Averager IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL stateControl                     : std_logic;
  SIGNAL stateControl_1                   : std_logic;
  SIGNAL enb_1_2_0_gated                  : std_logic;
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL count_step                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL modValue                         : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL count_reset                      : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL stateControl_3                   : std_logic;
  SIGNAL stateControl_4                   : std_logic;
  SIGNAL enb_1_2_0_gated_1                : std_logic;
  SIGNAL Fast_Counter_out1                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL count_from                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL count                            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL count_1                          : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL Delay_reg                        : vector_of_unsigned14(0 TO 13311);  -- ufix14 [13312]
  SIGNAL Delay_out1                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL signal_in_signed                 : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL Simple_Dual_Port_RAM_out1        : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL Simple_Dual_Port_RAM_out1_signed : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL Add_sub_cast                     : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL Add_sub_cast_1                   : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL Add_sub_temp                     : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- sfix16_En7
  SIGNAL Add1_out1                        : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL Delay1_reg                       : vector_of_signed32(0 TO 511);  -- sfix32 [512]
  SIGNAL Delay1_out1                      : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL Add1_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En4
  SIGNAL zero_1                           : std_logic;
  SIGNAL Fast_Counter_out2                : std_logic;
  SIGNAL stateControl_5                   : std_logic;
  SIGNAL stateControl_6                   : std_logic;
  SIGNAL enb_1_2_0_gated_2                : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL OR_out1                          : std_logic;

BEGIN
  u_Simple_Dual_Port_RAM : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 14,
                 DataWidth => 26
                 )
    PORT MAP( clk => clk,
              enb_1_2_0 => enb_1_2_0,
              wr_din => signal_in,
              wr_addr => std_logic_vector(Fast_Counter_out1),
              wr_en => valid_in,
              rd_addr => std_logic_vector(Delay_out1),
              dout => Simple_Dual_Port_RAM_out1
              );

  stateControl <= '1';

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      stateControl_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        stateControl_1 <= stateControl;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  enb_1_2_0_gated <= stateControl_1 AND enb_1_2_0;

  NOT_out1 <=  NOT valid_in;

  -- Modulo, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 13311
  count_step <= to_unsigned(16#0001#, 14);

  modValue <= to_unsigned(16#33FF#, 14);

  count_reset <= to_unsigned(16#0000#, 14);

  stateControl_3 <= '1';

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      stateControl_4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        stateControl_4 <= stateControl_3;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  enb_1_2_0_gated_1 <= stateControl_4 AND enb_1_2_0;

  count_from <= Fast_Counter_out1 - modValue;

  count <= Fast_Counter_out1 + count_step;

  
  need_to_wrap <= '1' WHEN Fast_Counter_out1 > to_unsigned(16#33FE#, 14) ELSE
      '0';

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  
  count_1 <= count_value WHEN NOT_out1 = '0' ELSE
      count_reset;

  Fast_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Fast_Counter_out1 <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0_gated_1 = '1' THEN
        Fast_Counter_out1 <= count_1;
      END IF;
    END IF;
  END PROCESS Fast_Counter_process;


  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_reg <= (OTHERS => to_unsigned(16#0000#, 14));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        Delay_reg(0) <= Fast_Counter_out1;
        Delay_reg(1 TO 13311) <= Delay_reg(0 TO 13310);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(13311);

  signal_in_signed <= signed(signal_in);

  Simple_Dual_Port_RAM_out1_signed <= signed(Simple_Dual_Port_RAM_out1);

  Add_sub_cast <= resize(signal_in_signed, 27);
  Add_sub_cast_1 <= resize(Simple_Dual_Port_RAM_out1_signed, 27);
  Add_sub_temp <= Add_sub_cast - Add_sub_cast_1;
  Add_out1 <= Add_sub_temp(23 DOWNTO 8);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_reg <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0_gated = '1' THEN
        Delay1_reg(0) <= Add1_out1;
        Delay1_reg(1 TO 511) <= Delay1_reg(0 TO 510);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(511);

  Add1_add_cast <= resize(Add_out1(15 DOWNTO 3), 32);
  Add1_out1 <= Delay1_out1 + Add1_add_cast;

  avg_out <= std_logic_vector(Add1_out1);

  zero_1 <= '0';

  
  Fast_Counter_out2 <= need_to_wrap WHEN NOT_out1 = '0' ELSE
      zero_1;

  stateControl_5 <= '1';

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      stateControl_6 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0 = '1' THEN
        stateControl_6 <= stateControl_5;
      END IF;
    END IF;
  END PROCESS delayMatch2_process;


  enb_1_2_0_gated_2 <= stateControl_6 AND enb_1_2_0;

  OR_out1 <= Delay2_out1 OR Fast_Counter_out2;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2_0_gated_2 = '1' THEN
        Delay2_out1 <= OR_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  valid_out <= Delay2_out1;

END rtl;

